added fallback versions to the installer

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -118,36 +118,44 @@ dotpaths="__top_dir__/.paths"
 
 # This function sets the variable "name_version" if not set already.
 # For preinstalled software, set "name_version" to "pre-installed".
+# If a third argument is given, this is the version to fall back to,
+# in case the second argument is "newest" and the newest version
+# cannot be determined.
 set_version()
 {
-    # Arguments: Program name, version
+    # Arguments: Program name, version, [fallback version]
     eval "[ -n \"\${${1}_version}\" ] || ${1}_version=\"${2}\""
     eval "[ \"\${${1}_preinstalled}\" != \"yes\" ] || ${1}_version=\"pre-installed\""
+    if [ -n "${3}" ]; then
+        eval "${1}_version_fallback=\"${3}\""
+    fi
 }
 # Specification of software versions. A specification of
 # "newest" will be replaced with the latest stable version.
-set_version "concept"         "newest"  # only newest        is known to work
-set_version "freetype"        "newest"  #      2.6           is known to work
-set_version "python"          "newest"  #      3.4.3         is known to work
-set_version "libpng"          "newest"  #      1.6.18        is known to work
-set_version "imagemagick"     "newest"  #      6.9.2-0       is known to work
-set_version "ncurses"         "newest"  #      6.0           is known to work
-set_version "openssl"         "newest"  #      1.0.2d        is known to work
-set_version "fftw"            "newest"  #      3.3.4         is known to work
-set_version "gadget"          "2.0.7"   # only 2.0.7         is known to work
-set_version "fftw_for_gadget" "2.1.5"   # only 2.1.5         is known to work
-set_version "gsl"             "newest"  #      1.16          is known to work
-set_version "hdf5"            "newest"  #      1.8.15-patch1 is known to work
-set_version "mpich"           "newest"  #      3.1.4         is known to work
-set_version "blessings"       "newest"  #      1.6           is known to work
-set_version "cython"          "0.22.1"  #      0.22.1        is known to work (0.23 does not work)
-set_version "cython_gsl"      "newest"  #      0.2.1         is known to work
-set_version "matplotlib"      "newest"  #      1.4.3         is known to work
-set_version "numpy"           "newest"  #      1.9.2         is known to work
-set_version "pexpect"         "newest"  #      3.3           is known to work
-set_version "mpi4py"          "newest"  #      1.3.1         is known to work
-set_version "h5py"            "newest"  #      2.5.0         is known to work
-set_version "zlib"            "newest"  #      1.2.8         is known to work
+# Programs:
+set_version "concept"         "newest"                  # only newest is known to work
+set_version "freetype"        "newest" "2.6"
+set_version "python"          "newest" "3.4.3"
+set_version "libpng"          "newest" "1.6.18"
+set_version "imagemagick"     "newest" "6.9.2-0"
+set_version "ncurses"         "newest" "6.0"
+set_version "openssl"         "newest" "1.0.2d"
+set_version "fftw"            "newest" "3.3.4"
+set_version "gadget"          "2.0.7"                   # only 2.0.7  is known to work
+set_version "fftw_for_gadget" "2.1.5"                   # only 2.1.5  is known to work
+set_version "gsl"             "newest" "1.16"
+set_version "hdf5"            "newest" "1.8.15-patch1"
+set_version "mpich"           "newest" "3.1.4"
+# Python packages:
+set_version "blessings"       "newest"                  #      1.6    is known to work
+set_version "cython"          "0.22.1"                  #      0.22.1 is known to work (0.23 does not work)
+set_version "cython_gsl"      "newest"                  #      0.2.1  is known to work
+set_version "matplotlib"      "newest"                  #      1.4.3  is known to work
+set_version "numpy"           "newest"                  #      1.9.2  is known to work
+set_version "pexpect"         "newest"                  #      3.3    is known to work
+set_version "mpi4py"          "newest"                  #      1.3.1  is known to work
+set_version "h5py"            "newest"                  #      2.5.0  is known to work
+set_version "zlib"            "newest"                  #      1.2.8  is known to work
 
 
 
@@ -281,8 +289,8 @@ check_system_dependency()
                     case $yn in
                         [Yy]* ) sudo apt-get -y install ${3}; printf "${1} successfully installed\n\n"; return;;
                         [Nn]* ) error "Terminated install due to missing component '${1}'"; exit 1;;
-                        "" ) sudo apt-get -y install ${3}; printf "${1} successfully installed\n\n"; return;;
-                        * ) "Terminated install due to missing component '${1}'"; exit 1;;
+                        "" )    sudo apt-get -y install ${3}; printf "${1} successfully installed\n\n"; return;;
+                        * )     error "Terminated install due to missing component '${1}'"; exit 1;;
                     esac
                 done
             fi
@@ -435,9 +443,9 @@ validate_url()
     # Arguments: Program name
     current_step="validation of ${1/CONCEPT/$esc_concept} link"
     set_status "Validating ${1/CONCEPT/$esc_concept_double_backslashes} link"
-    varname="${1,,}"
-    varname="${varname// /_}"
-    url="$(eval "echo \"\${${varname}_url}\"")"
+    progname="${1,,}"
+    progname="${progname// /_}"
+    url="$(eval "echo \"\${${progname}_url}\"")"
     text=$(wget -t 50 --timeout 15 -S --spider "${url}" 2>&1)
     text_http=$(echo "${text}" | grep "Remote file exists" || :)
     filename=$(basename "${url}")
@@ -448,6 +456,28 @@ validate_url()
     fi
 }
 
+# Function for letting versions fall back to their fallback values,
+# in case of unsuccessful retrievel of newest version nu.
+fallback()
+{
+    # Arguments: Program name
+    progname="${1,,}"
+    progname="${progname// /_}"
+    eval "progname_version=\"\${${progname}_version}\""
+    eval "progname_version_fallback=\"\${${progname}_version_fallback}\""
+    if [ -z "${progname_version}" ]; then
+        if [ -z "${progname_version_fallback}" ]; then
+            exit 1
+        fi
+        error "Warning: Could not identify the version number of the latest ${1}!\n" 2>&1
+        printf "${esc_up}${esc_up}"
+        error "Falling back to ${1} version ${progname_version_fallback}" 2>&1
+        progname_version="${progname_version_fallback}"
+        eval "${progname}_version=\"\${progname_version}\""
+        eval "${progname}_version_fallback=\"\${progname_version_fallback}\""
+    fi
+}
+
 # FreeType
 if [ "${python_preinstalled}" == "no" ] && [ "${freetype_preinstalled}" == "no" ]; then
     if [ "${freetype_version}" == "newest" ]; then
@@ -455,10 +485,7 @@ if [ "${python_preinstalled}" == "no" ] && [ "${freetype_preinstalled}" == "no" 
         set_status "Searching for latest version of FreeType"
         freetype_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "http://download.savannah.gnu.org/releases/freetype/" | grep -o "freetype-[0-9.]*tar" | sort -u | tail -n 1 | grep -o [0-9.]* || :)"
         freetype_version="${freetype_version%?}"
-        if [ -z "${freetype_version}" ]; then
-            error "Error: Could not identify the version number of the latest FreeType!"
-            exit 1
-        fi
+        fallback "FreeType"
     fi
     freetype_url="http://download.savannah.gnu.org/releases/freetype/freetype-${freetype_version}.tar.gz"
     validate_url "FreeType"
@@ -470,10 +497,7 @@ if ([ "${imagemagick_preinstalled}" == "no" ] || [ "${python_preinstalled}" == "
         current_step="search for latest version of zlib"
         set_status "Searching for latest version of zlib"
         zlib_version=$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "http://sourceforge.net/projects/libpng/files/zlib/" | grep -o "zlib/[0-9.]*" | grep -o "[0-9.]*" | sort -u | tail -n 1 || :)
-        if [ -z "${zlib_version}" ]; then
-            error "Error: Could not identify the version number of the latest zlib!"
-            exit 1
-        fi
+        fallback "zlib"
     fi
     zlib_url="http://sourceforge.net/projects/libpng/files/zlib/${zlib_version}/zlib-${zlib_version}.tar.gz"
     validate_url "zlib"
@@ -486,10 +510,7 @@ if ([ "${imagemagick_preinstalled}" == "no" ] || [ "${python_preinstalled}" == "
         libpng_version_majors="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "ftp://ftp.simplesystems.org/pub/png/src/" | grep -o "libpng[0-9]*" | grep -o "[0-9]*" | sort -u | tail -n 1 || :)"
         libpng_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "ftp://ftp.simplesystems.org/pub/png/src/libpng${libpng_version_majors}/" | grep -o "libpng-[0-9\.]*.tar.gz" | sort -u | tail -n 1 | grep -o "[0-9\.]*" | head -n 1 || :)"
         libpng_version="${libpng_version:0:${#libpng_version}-1}"
-        if [ -z "${libpng_version}" ]; then
-            error "Error: Could not identify the version number of the latest libpng!"
-            exit 1
-        fi
+        fallback "libpng"
     fi
     libpng_url="ftp://ftp.simplesystems.org/pub/png/src/libpng${libpng_version_majors}/libpng-${libpng_version}.tar.gz"
     validate_url "libpng"
@@ -500,10 +521,7 @@ if [ "${imagemagick_preinstalled}" == "no" ]; then
     if [ "${imagemagick_version}" == "newest" ]; then
         imagemagick_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "http://www.imagemagick.org/download/releases/" | grep -o "ImageMagick[0-9\.\-]*.tar" | grep -o "[0-9\.\-]*" | sort -u | tail -n 1 || :)"
         imagemagick_version="${imagemagick_version:1:${#limagemagick_version}-1}"
-        if [ -z "${imagemagick_version}" ]; then
-            error "Error: Could not identify the version number of the latest ImageMagick!"
-            exit 1
-        fi
+        fallback "ImageMagick"
     fi
     imagemagick_url="http://www.imagemagick.org/download/releases/ImageMagick-${imagemagick_version}.tar.gz"
     validate_url "ImageMagick"
@@ -516,10 +534,7 @@ if [ "${python_preinstalled}" == "no" ] && [ "${ncurses_preinstalled}" == "no" ]
         set_status "Searching for latest version of ncurses"
         ncurses_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "http://ftp.gnu.org/pub/gnu/ncurses/" | grep -o "ncurses-[0-9.]*tar" | sort -u | tail -n 1 | grep -o [0-9.]* || :)"
         ncurses_version="${ncurses_version%?}"
-        if [ -z "${ncurses_version}" ]; then
-            error "Error: Could not identify the version number of the latest ncurses!"
-            exit 1
-        fi
+        fallback "ncurses"
     fi
     ncurses_url="http://ftp.gnu.org/pub/gnu/ncurses/ncurses-${ncurses_version}.tar.gz"
     validate_url "ncurses"
@@ -532,10 +547,7 @@ if [ "${python_preinstalled}" == "no" ] && [ "${openssl_preinstalled}" == "no" ]
         set_status "Searching for latest version of OpenSSL"
         openssl_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "ftp://ftp.openssl.org/source/" | grep "openssl-[0-9].*.tar.gz" | tail -n 1 | grep -o -P "(?<=openssl-).*(?=.tar.gz)" | grep -o -P "(?=[0-9]).*(?=.tar.gz)" || :)"
         openssl_version="$(sed 's/.tar.gz.*//' <<< "${openssl_version}")"
-        if [ -z "${openssl_version}" ]; then
-            error "Error: Could not identify the version number of the latest OpenSSL!"
-            exit 1
-        fi
+        fallback "OpenSSL"
     fi
     openssl_url="ftp://ftp.openssl.org/source/openssl-${openssl_version}.tar.gz"
     validate_url "OpenSSL"
@@ -547,10 +559,7 @@ if [ "${python_preinstalled}" == "no" ]; then
         current_step="search for latest version of Python"
         set_status "Searching for latest version of Python"
         python_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "https://www.python.org/downloads/" | grep -o -P "(?<=Python-).*(?=.tar)" | head -1  || :)"
-        if [ -z "${python_version}" ]; then
-            error "Error: Could not identify the version number of the latest Python!"
-            exit 1
-        fi
+        fallback "Python"
     fi
     python_url="https://www.python.org/ftp/python/${python_version}/Python-${python_version}.tgz"
     validate_url "Python"
@@ -562,10 +571,7 @@ if [ "${gsl_preinstalled}" == "no" ]; then
         current_step="search for latest version of GSL"
         set_status "Searching for latest version of GSL"
         gsl_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "ftp://ftp.gnu.org/gnu/gsl/" | grep "gsl-latest.tar.gz" | grep -o "gsl-[0-9.]*tar.gz" |  grep -o "[0-9][0-9.]*[0-9]" || :)"
-        if [ -z "${gsl_version}" ]; then
-            error "Error: Could not identify the version number of the latest GSL!"
-            exit 1
-        fi
+        fallback "GSL"
     fi
     gsl_url="ftp://ftp.gnu.org/gnu/gsl/gsl-${gsl_version}.tar.gz"
     validate_url "GSL"
@@ -577,10 +583,7 @@ if [ "${mpi_preinstalled}" == "no" ]; then
         current_step="search for latest version of MPICH"
         set_status "Searching for latest version of MPICH"
         mpich_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "http://www.mpich.org/downloads" | grep -m 1 -o -P "(?<=mpich-).*(?=stable)" | awk '{print $1}' || :)"
-        if [ -z "${mpich_version}" ]; then
-            error "Error: Could not identify the version number of the latest MPICH!"
-            exit 1
-        fi
+        fallback "MPICH"
     fi
     mpich_url="http://www.mpich.org/static/downloads/${mpich_version}/mpich-${mpich_version}.tar.gz"
     validate_url "MPICH"
@@ -592,10 +595,7 @@ if [ "${hdf5_preinstalled}" == "no" ]; then
         current_step="search for latest version of HDF5"
         set_status "Searching for latest version of HDF5"
         hdf5_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "ftp://ftp.hdfgroup.org/HDF5/current/src/" | grep -m 1 -o -P "(?<=hdf5-).*(?=.tar\")" || :)"
-        if [ -z "${hdf5_version}" ]; then
-            error "Error: Could not identify the version number of the latest HDF5!"
-            exit 1
-        fi
+        fallback "HDF5"
     fi
     hdf5_url="ftp://ftp.hdfgroup.org/HDF5/releases/hdf5-${hdf5_version}/src/hdf5-${hdf5_version}.tar.gz"
     validate_url "HDF5"
@@ -607,10 +607,7 @@ if [ "${fftw_preinstalled}" == "no" ]; then
         current_step="search for latest version of FFTW"
         set_status "Searching for latest version of FFTW"
         fftw_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "http://www.fftw.org/download.html" | grep -m 1 -o -P "(?<=fftw-).*(?=.tar.gz\")" || :)"
-        if [ -z "${fftw_version}" ]; then
-            error "Error: Could not identify the version number of the latest FFTW!"
-            exit 1
-        fi
+        fallback "FFTW"
     fi
     fftw_url="http://www.fftw.org/fftw-${fftw_version}.tar.gz"
     validate_url "FFTW"
@@ -643,10 +640,7 @@ if [ "${fftw_for_gadget_preinstalled}" == "no" ]; then
         current_step="search for latest version of FFTW for GADGET"
         set_status "Searching for latest version of FFTW for GADGET"
         fftw_for_gadget_version="$(wget -t 50 --timeout 15 -q -O- --no-check-certificate "http://www.fftw.org/download.html" | grep -m 1 -o -P "(?<=fftw-).*(?=.tar.gz\")" || :)"
-        if [ -z "${fftw_for_gadget_version}" ]; then
-            error "Error: Could not identify the version number of the latest FFTW"
-            exit 1
-        fi
+        fallback "fftw_for_gadget"
     fi
     fftw_for_gadget_url="http://www.fftw.org/fftw-${fftw_for_gadget_version}.tar.gz"
     validate_url "FFTW for GADGET"
@@ -1416,11 +1410,15 @@ fi
 
 # Run complete CONCEPT test suite if basic CONCEPT test finished successfully
 if [ "${concept_test_success}" == "yes" ]; then
+    current_step="testing of ${esc_concept}"
+    heading "Testing ${esc_concept}"
+    set_status "Testing ${esc_concept_double_backslashes}"
     ./run -t all 2>&1 | tee "test_log"
     [ ${PIPESTATUS[0]} != 0 ] && concept_test_success="no"
     # Clean test_log if test is successfull
     if [ "${concept_test_success}" == "yes" ]; then
         rm "test_log"
+        make distclean
     fi
 fi
 cd "${top_dir}"
@@ -1439,6 +1437,7 @@ copyright_notice()
         echo
     fi
 }
+disable_status
 current_step="copyright notice"
 heading "Copyright notice"
 msg="${esc_concept} has been installed along with the following dependencies:
@@ -1476,14 +1475,20 @@ printf "${msg}"
 
 # Notice about test errors
 current_step="erroneous tests notice"
+any_test_error_notices="no"
 erroneous_test_notice()
 {
     # Arguments: Program name
     progname="${1// /_}"
     progname="${progname,,}"
     test_success="yes"
-    eval "[ ${progname}_test_success == 'no' ] && test_success='no'"
-    if [ test_success == "no" ]; then
+    eval "[ \"\${${progname}_test_success}\" == 'no' ] && test_success='no'"
+    if [ ${test_success} == "no" ]; then
+        if [ "${any_test_error_notices}" == "no" ]; then
+            # First test error notive
+            heading "Erroneous tests notice"
+            any_test_error_notices="yes"
+        fi
         eval "test_log_path=\"\${${progname}_dir}/test_log\""
         printf "\nWarning: Some tests of ${1} did not pass successfully.\n"
         printf "As ${1} did seem to install correctly, this is usually not of any concern.\n"
@@ -1505,7 +1510,6 @@ erroneous_test_notice "OpenSSL"
 erroneous_test_notice "Python"
 erroneous_test_notice "zlib"
 if [ "${concept_test_success}" == "no" ]; then
-disable_status
 error "\nWarning: Some tests of ${esc_concept} did not pass successfully.
 This should usually be taken seriously.
 The logged output of the tests can be found in
