adopted Python 3.8

diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -358,12 +358,12 @@ set_version "libpng"           "1.6.37" "1.6.37"
 if [ "${mpi}" == "mpich" ]; then
     set_version "mpi"          "3.3.1"  "3.3.1"
 elif [ "${mpi}" == "openmpi" ]; then
-    set_version "mpi"          "4.0.1"
+    set_version "mpi"          "4.0.2"
 fi
 set_version "ncurses"          "6.1"    "6.1"
 set_version "openssl"          "1.1.1d" "1.1.1d"
 set_version "perl"             "5.30.0"
-set_version "python"           "3.7.4"
+set_version "python"           "3.8.0"
 set_version "zlib"             "1.2.11" "1.2.11"
 # Python packages
 set_version "blessings"        "1.7"
@@ -372,11 +372,11 @@ set_version "cythongsl"        "0.2.2"
 set_version "h5py"             "2.10.0"
 set_version "matplotlib"       "3.1.1"
 set_version "mpi4py"           "3.0.2"
-set_version "numpy"            "1.17.2"
-set_version "pip"              "19.2.3"
-set_version "pytest"           "5.1.3"
+set_version "numpy"            "1.17.3"
+set_version "pip"              "19.3.1"
+set_version "pytest"           "5.2.1"
 set_version "scipy"            "1.3.1"
-set_version "setuptools"       "41.2.0"
+set_version "setuptools"       "41.4.0"
 set_version "sphinx"           "2.2.0"
 set_version "sphinx_rtd_theme" "0.4.3"
 set_version "wheel"            "0.33.6"
@@ -5325,13 +5325,24 @@ disable_atomic_operations=${disable_atomic_operations}, pyoptimizations=${pyopti
                     export LD_LIBRARY_PATH="${openssl_dir}/lib:${LD_LIBRARY_PATH}"
                     export LDFLAGS="-L${openssl_dir}/lib -Wl,-rpath=${openssl_dir}/lib ${LDFLAGS}"
                     with_openssl="--with-openssl=${openssl_dir}"
-                    # Modify Modules/Setup.dist in order for Python to use the
+                    # Modify Modules/Setup (Modules/Setup.dist in older
+                    # Python versions) in order for Python to use the
                     # custom SSL library.
-                    first_line="$(grep -n 'SSL=' 'Modules/Setup.dist')"
-                    first_line=${first_line%:*}
-                    ((last_line = first_line + 3))
-                    sed -i "${first_line},${last_line}s/.//" "Modules/Setup.dist"
-                    sed -i "${first_line}s/.*/SSL=${openssl_dir//\//\\/}/" "Modules/Setup.dist"
+                    modules_setup_filename=""
+                    for setup_filename in "Setup" "Setup.dist"; do
+                        if [ -f "Modules/${setup_filename}" ]; then
+                            modules_setup_filename="Modules/${setup_filename}"
+                            break
+                        fi
+                    done
+                    if [ -n "${modules_setup_filename}" ]; then
+                        first_line="$(grep -n "SSL=" "${modules_setup_filename}")"
+                        first_line=${first_line%:*}
+                        ((last_line = first_line + 3))
+                        sed -i "${first_line},${last_line}s/.//" "${modules_setup_filename}"
+                        sed -i "${first_line}s/.*/SSL=${openssl_dir//\//\\/}/" \
+                            "${modules_setup_filename}"
+                    fi
                 fi
                 if [ -n "${zlib_dir}" ]; then
                     export CPPFLAGS="-I${zlib_dir}/include ${CPPFLAGS}"
@@ -5362,6 +5373,7 @@ ${CPPFLAGS}"
                     cd "${current_dir}"
                     with_system_ffi="--with-system-ffi"
                 fi
+                export LDFLAGS="-L${python_dir}/lib -Wl,--rpath=${python_dir}/lib ${LDFLAGS}"
                 # Configure.
                 # When pgo optimizations are enabled, some of the tests which
                 # are performed may hang. It appears that the configure script
@@ -5564,6 +5576,7 @@ pip_install_pypackage(){
     # If second argument is not provided, the newest version
     # will be installed.
     local command_end=""
+    pypackage_version=""
     if [ "${2}" == "upgrade" ]; then
         current_step="upgrade of ${1}"
         heading "Upgrading ${1}"
@@ -5579,7 +5592,8 @@ pip_install_pypackage(){
             set_status "Installing ${1}"
         fi
         if [ -n "${2}" ]; then
-            command_end="==${2}"
+            pypackage_version="${2}"
+            command_end="==${pypackage_version}"
         fi
     fi
     # Download Python package source
@@ -5596,37 +5610,136 @@ pip_install_pypackage(){
     if [ "${2}" == "upgrade" ]; then
         upgrade_flag="--upgrade"
     fi
-    for pyuser in "" "--user"; do
-        # After the adoption of PEP 518 (pip 10), some packages require
-        # wheels (not bare source) when building. This can be disabled by
-        # supplying --no-build-isolation. We try both.
-        # Some times the installation process will appear to hang,
-        # but it will eventually get going. This happens often for
-        # particular packages, such as h5py. When this is the case,
-        # write a soothing message.
-        for extra_pip_arg in ""    \
-            "--no-build-isolation" \
-            "--no-cache-dir"       \
-            "--no-build-isolation --no-cache-dir"; do
-            if [ -n "${extra_pip_arg}" ]; then
-                printf "\npip failed to install ${1}. \
+    for force_recythonization in "False" "True"; do
+        if [ "${force_recythonization}" == "True" ]; then
+            # Some Python packages may contain pre-cythonized files as
+            # part of their source code. If this is done with a Cython
+            # version that is incompatible with the Python version in
+            # use, this can lead to failure. We now try deleting any
+            # such pre-cythonized files, forcing re-cythonization.
+            working_cython=$(check_pypackage_installed cython)
+            if [ "${working_cython}" == "False" ]; then
+                continue
+            fi
+            rm -rf "${tmp_pip_dir}" || :
+            cp -r "${tmp_pip_dir}_cp" "${tmp_pip_dir}"
+            # Extract source files
+            wd="$(pwd)"
+            cd "${tmp_pip_dir}"
+            pypackage_archive=""
+            for f in *; do
+                f_lower="$(echo "${f}" | tr '[:upper:]' '[:lower:]')"
+                if [ ! -d "${f}" ] && [[ "${f_lower}" == "${pypackage}"* ]]; then
+                    pypackage_archive="${f}"
+                    break
+                fi
+            done
+            extract "${pypackage_archive}" "True"
+            for f in *; do
+                f_lower="$(echo "${f}" | tr '[:upper:]' '[:lower:]')"
+                if [ -d "${f}" ] && [[ "${f_lower}" == "${pypackage}"* ]]; then
+                    cd "${f}"
+                    break
+                fi
+            done
+            # Remove pre-cythonized files
+            precythonized="$(grep -r -l '^/\* Generated by Cython' .)"
+            if [ -z "${precythonized}" ]; then
+                cd "${wd}"
+                continue
+            fi
+            rm -f ${precythonized}
+            # Pack source into a tar.gz file with the name
+            # <package>-<version>.tar.gz, which takes the place of the
+            # downloaded archive.
+            cd ..
+            rm -rf "${pypackage_archive}"
+            if [ -n "${pypackage_version}" ]; then
+                pypackage_archive="${pypackage}-${pypackage_version}.tar.gz"
+            else
+                pypackage_archive="${pypackage}.tar.gz"
+            fi
+            tar -cvf - "${f}" | gzip > "${pypackage_archive}"
+            rm -rf "${f}"
+            cd "${wd}"
+            rm -rf "${tmp_pip_dir}_cp" || :
+            cp -r "${tmp_pip_dir}" "${tmp_pip_dir}_cp"
+            # The re-cythonization should be carried out using the
+            # Cython that is installed on the Python that we work with.
+            # It may however be fetched from the PATH, and so we need to
+            # ensure that the first Cython ('cython', 'cythonize') on
+            # the PATH is the correct one.
+            if [ -d "${python_dir}/bin" ]; then
+                export PATH="${python_dir}/bin:${PATH}"
+            fi
+        fi
+        for pyuser in "" "--user"; do
+            # After the adoption of PEP 518 (pip 10), some packages
+            # require wheels (not bare source) when building. This can
+            # be disabled by supplying --no-build-isolation. We try
+            # both. Some times the installation process will appear to
+            # hang, but it will eventually get going. This happens often
+            # for particular packages, such as h5py. When this is the
+            # case, write a soothing message.
+            for extra_pip_arg in "--no-cache-dir"     \
+                "--no-cache-dir --no-build-isolation" \
+                "--no-build-isolation"                \
+                ""; do
+                if [ -n "${extra_pip_arg}" ]; then
+                    printf "\npip failed to install ${1}. \
 Now trying with ${pyuser} ${extra_pip_arg}\n\n"
+                fi
                 rm -rf "${tmp_pip_dir}" || :
                 cp -r "${tmp_pip_dir}_cp" "${tmp_pip_dir}"
+                if [ -z "${upgrade_flag}" ]; then
+                    printf "
+Attempting to install ${1} using pip with force_recythonization=${force_recythonization}, \
+pyuser=${pyuser}, extra_pip_arg=${extra_pip_arg}\n\n"
+                    "${python}" -m pip uninstall "${pypackage}" -y >/dev/null 2>&1 || :
+                fi
+                "${python}" -m pip install ${pyuser} -v -v -v                \
+                                           ${extra_pip_arg}                  \
+                                           -b "${tmp_pip_dir}/build"         \
+                                           ${upgrade_flag}                   \
+                                           --no-index                        \
+                                           --find-links="${tmp_pip_dir}"     \
+                                           "${pypackage}${command_end}" 2>&1 \
+                                            & pip_install_pid=$!
+                soothe ${pip_install_pid}
+                pypackage_installed=$(check_pypackage_installed ${pypackage})
+                if [ "${pypackage_installed}" == "True" ]; then
+                    break
+                fi
+            done
+            if [ "${pypackage_installed}" == "True" ]; then
+                break
             fi
-            if [ -z "${upgrade_flag}" ]; then
-                "${python}" -m pip uninstall "${pypackage}" -y >/dev/null 2>&1 || :
+            # If we failed to install the Python package,
+            # try installing it via pip without supplying
+            # the many additional arguments.
+            if [ "${force_recythonization}" == "True" ]; then
+                continue
             fi
-            "${python}" -m pip install ${pyuser} -v -v -v                \
-                                       ${extra_pip_arg}                  \
-                                       -b "${tmp_pip_dir}/build"         \
-                                       ${upgrade_flag}                   \
-                                       --no-index                        \
-                                       --find-links="${tmp_pip_dir}"     \
-                                       "${pypackage}${command_end}" 2>&1 \
-                                        & pip_install_pid=$!
-            soothe ${pip_install_pid}
-            pypackage_installed=$(check_pypackage_installed ${pypackage})
+            rm -rf "${tmp_pip_dir}" || :
+            for extra_pip_arg in "--no-cache-dir"     \
+                "--no-cache-dir --no-build-isolation" \
+                "--no-build-isolation"                \
+                ""; do
+                printf "
+Attempting to install ${1} using pip with default settings, \
+force_recythonization=${force_recythonization}, pyuser=${pyuser}, \
+extra_pip_arg=${extra_pip_arg}\n\n"
+                if [ -z "${upgrade_flag}" ]; then
+                    "${python}" -m pip uninstall "${pypackage}" -y >/dev/null 2>&1 || :
+                fi
+                "${python}" -m pip install ${pyuser} ${extra_pip_arg} \
+                    "${pypackage}${command_end}" 2>&1 & pip_install_pid=$!
+                soothe ${pip_install_pid}
+                pypackage_installed=$(check_pypackage_installed ${pypackage})
+                if [ "${pypackage_installed}" == "True" ]; then
+                    break
+                fi
+            done
             if [ "${pypackage_installed}" == "True" ]; then
                 break
             fi
@@ -5634,31 +5747,6 @@ Now trying with ${pyuser} ${extra_pip_arg}\n\n"
         if [ "${pypackage_installed}" == "True" ]; then
             break
         fi
-        rm -rf "${tmp_pip_dir}"
-        # If we failed to install the Python package, try installing it
-        # via pip without using any additional arguments.
-        printf "\npip could not install/upgrade ${1}, neither with or without \
---no-build-isolation and --no-cache-dir\nNow trying without specifying any \
-extra arguments to pip\n\n"
-        if [ -z "${upgrade_flag}" ]; then
-            "${python}" -m pip uninstall "${pypackage}" -y >/dev/null 2>&1 || :
-        fi
-        "${python}" -m pip install ${pyuser} "${pypackage}${command_end}" 2>&1 & pip_install_pid=$!
-        soothe ${pip_install_pid}
-        pypackage_installed=$(check_pypackage_installed ${pypackage})
-        if [ "${pypackage_installed}" == "True" ]; then
-            break
-        fi
-        # If we still fail, try with just the --no-cache-dir argument
-        printf "\npip could not install/upgrade ${1} using no additional arguments\n\
-Now trying with just --no-cache-dir\n\n"
-        if [ -z "${upgrade_flag}" ]; then
-            "${python}" -m pip uninstall "${pypackage}" -y >/dev/null 2>&1 || :
-        fi
-        "${python}" -m pip install ${pyuser} --no-cache-dir \
-            "${pypackage}${command_end}" 2>&1 & pip_install_pid=$!
-        soothe ${pip_install_pid}
-        pypackage_installed=$(check_pypackage_installed ${pypackage})
     done
     reset_environment
     # Exit on failure
