✨ clang support (#219)

diff --git a/concept/Makefile b/concept/Makefile
--- a/concept/Makefile
+++ b/concept/Makefile
@@ -69,7 +69,7 @@ files_auxiliary =      \
     ../install_log     \
     ../install_log_err \
     .exit_code_*       \
-    .lto_test.*        \
+    .lto_test*         \
     jobscript          \
 
 # List of files and directories in the utilities directory
@@ -176,17 +176,19 @@ compiler = $(shell                                           \
         echo "icc";                                          \
     elif echo "$${info}" | grep -i gcc >/dev/null; then      \
         echo "gcc";                                          \
+    elif echo "$${info}" | grep -i clang >/dev/null; then    \
+        echo "clang";                                        \
     else                                                     \
         echo "gcc";                                          \
     fi                                                       \
 )
-python_cflags = $(filter-out             \
-    $(addprefix -W,$(unwanted_warnings)) \
-    -g -g0 -g1 -g2 -g3                   \
-    -O -O0 -O1 -O2 -O3 -Og -Os -Ofast    \
-    -fwrapv                              \
-    ,                                    \
-    $(shell $(python_config) --cflags)   \
+python_cflags = $(filter-out              \
+    $(addprefix -W,$(unwanted_warnings))  \
+    -g -g0 -g1 -g2 -g3                    \
+    -O -O0 -O1 -O2 -O3 -O4 -Og -Os -Ofast \
+    -fwrapv                               \
+    ,                                     \
+    $(shell $(python_config) --cflags)    \
 )
 unwanted_warnings_general += \
     uninitialized            \
@@ -220,6 +222,8 @@ ifneq ($(no_optimizations),True)
     # Floating-point optimizations
     ifeq ($(compiler),gcc)
         optimizations += -ffast-math
+    else ifeq ($(compiler),clang)
+        optimizations += -ffast-math
     else ifeq ($(compiler),icc)
         optimizations += -fp-model fast=2
     endif
@@ -237,7 +241,9 @@ ifneq ($(no_optimizations),True)
     lto_warning = $(shell                                           \
         echo "int main(void){ return 0; }" > .lto_test.c;           \
         $(CC) -flto -c -o .lto_test.o .lto_test.c 2>&1 | grep flto; \
-        $(RM) -f .lto_test.c .lto_test.o                            \
+        $(CC) .lto_test.o -o .lto_test -flto      2>&1 | grep flto; \
+        ./.lto_test 2>/dev/null || echo "lto error";                \
+        $(RM) -f .lto_test.c .lto_test.o .lto_test;                 \
     )
     ifeq ("$(lto_warning)","")
         optimizations        += -flto
diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -2180,6 +2180,11 @@ try:
     elif '${pypackage}' == 'pythondateutil':
         # Python-dateutil is imported as dateutil
         import dateutil
+    elif '${pypackage}' == 'matplotlib':
+        # For Matplotlib we do a more thorough test
+        import matplotlib
+        matplotlib.use('agg')
+        import matplotlib.pyplot as plt
     elif '${pypackage}' == 'mpi4py':
         # For MPI4Py we do a more thorough test
         import mpi4py.rc; mpi4py.rc.threads = False  # Do not use threads
@@ -2187,6 +2192,12 @@ try:
     elif '${pypackage}' == 'pillow':
         # Pillow is imported as PIL
         import PIL
+    elif '${pypackage}' == 'scipy':
+        # For SciPy we do a more thorough test
+        import scipy.interpolate
+        import scipy.optimize
+        import scipy.signal
+        import scipy.special
     else:
         import ${pypackage}
     sleep(1)
@@ -5360,10 +5371,13 @@ set_optimizations() {
         use_lto="False"
     fi
     # Determine the compiler in use.
-    # Only icc and gcc are implemented here. The gcc behaviour
-    # is chosen if some third compiler is really in use.
+    # The gcc behaviour is chosen if some compiler
+    # not specified here is really in use.
+    CC_implementation="gcc"
     if [ "${compiler}" == "gnu" ]; then
         CC_implementation="gcc"
+    elif [ "${compiler}" == "clang" ]; then
+        CC_implementation="clang"
     elif [ "${compiler}" == "intel" ]; then
         CC_implementation="icc"
     else
@@ -5372,16 +5386,17 @@ set_optimizations() {
             CC_implementation="icc"
         elif echo "${info}" | grep -i "intel" >/dev/null; then
             CC_implementation="icc"
-        else
-            # Assume gcc
+        elif echo "${info}" | grep -i "gcc" >/dev/null; then
             CC_implementation="gcc"
+        elif echo "${info}" | grep -i "clang" >/dev/null; then
+            CC_implementation="clang"
         fi
     fi
     # General optimizations
     optimizations="-DNDEBUG -O3 -funroll-loops"
     optimizations_linker="-O3"
     # Floating point optimizations
-    if [ "${CC_implementation}" == "gcc" ]; then
+    if [ "${CC_implementation}" == "gcc" ] || [ "${CC_implementation}" == "clang" ]; then
         optimizations="${optimizations} -ffast-math"
     elif [ "${CC_implementation}" == "icc" ]; then
         optimizations="${optimizations} -fp-model fast=2"
@@ -5401,7 +5416,11 @@ set_optimizations() {
         mkdir -p "${lto_test_dir}"
         cd "${lto_test_dir}"
         echo "int main(void){ return 0; }" > main.c
-        lto_warning=$("${CC}" -flto -c -o main.o main.c 2>&1 | grep flto || :)
+        lto_warning="$(                                              \
+            "${CC}" -flto -c -o main.o main.c 2>&1 | grep flto || :; \
+            "${CC}" main.o -o main -flto 2>&1      | grep flto || :; \
+            ./main 2>/dev/null || echo "lto error";                  \
+        )"
         cd "${current_dir}"
         rm -rf "${lto_test_dir}" || :
         if [ -z "${lto_warning}" ]; then
@@ -5410,9 +5429,9 @@ set_optimizations() {
         fi
     fi
     # Remove unwanted flags from CFLAGS and CXXFLAGS
-    unwanted_flags=(                      \
-        -g -g0 -g1 -g2 -g3                \
-        -O -O0 -O1 -O2 -O3 -Og -Os -Ofast \
+    unwanted_flags=(                          \
+        -g -g0 -g1 -g2 -g3                    \
+        -O -O0 -O1 -O2 -O3 -O4 -Og -Os -Ofast \
     )
     CFLAGS_ori="${CFLAGS}"
     CFLAGS=""
