improve robustness of installation and workflows; bump dependencies (#237)

diff --git a/concept/Makefile b/concept/Makefile
--- a/concept/Makefile
+++ b/concept/Makefile
@@ -25,6 +25,7 @@
 # build and run the code.
 # This makefile accepts the options
 #   native_optimizations
+#   no_lto
 #   no_optimizations
 #   unsafe_building
 # all of which may be either 'True' or 'False',
@@ -238,16 +239,18 @@ ifneq ($(no_optimizations),True)
         optimizations += -march=native
     endif
     # Link time optimizations
-    lto_warning = $(shell                                           \
-        echo "int main(void){ return 0; }" > .lto_test.c;           \
-        $(CC) -flto -c -o .lto_test.o .lto_test.c 2>&1 | grep flto; \
-        $(CC) .lto_test.o -o .lto_test -flto      2>&1 | grep flto; \
-        ./.lto_test 2>/dev/null || echo "lto error";                \
-        $(RM) -f .lto_test.c .lto_test.o .lto_test;                 \
-    )
-    ifeq ("$(lto_warning)","")
-        optimizations        += -flto
-        optimizations_linker += -flto
+    ifneq ($(no_lto),True)
+        lto_warning = $(shell                                           \
+            echo "int main(void){ return 0; }" > .lto_test.c;           \
+            $(CC) -flto -c -o .lto_test.o .lto_test.c 2>&1 | grep flto; \
+            $(CC) .lto_test.o -o .lto_test -flto      2>&1 | grep flto; \
+            ./.lto_test 2>/dev/null || echo "lto error";                \
+            $(RM) -f .lto_test.c .lto_test.o .lto_test;                 \
+        )
+        ifeq ("$(lto_warning)","")
+            optimizations        += -flto
+            optimizations_linker += -flto
+        endif
     endif
 endif
 CFLAGS += $(call unique, $(call sensible_paths, \
@@ -307,28 +310,35 @@ LDFLAGS += $(call unique, $(call sensible_paths,     \
 # The below recipes are responsible for the
 # .py --> ((.pyx --> types) --> .pxd) --> (.c + .html) --> .o --> .so
 # build chain. A heading is printed at the beginning of the build.
-building = modules
 define heading
-    $(python) -B -c "pass;                                                              \
-        import sys;                                                                     \
-        from time import sleep;                                                         \
-        import blessings;                                                               \
-        sys.exit() if '$(heading_printed)' else None;                                   \
-        extra = [];                                                                     \
-        extra.append('native optimizations')                                            \
-            if '$(native_optimizations)' == 'True' and '$(no_optimizations)' == 'False' \
-            else None;                                                                  \
-        extra.append('no optimizations')                                                \
-            if '$(no_optimizations)' == 'True'                                          \
-            else None;                                                                  \
-        extra.append('unsafe')                                                          \
-            if '$(unsafe_building)' == 'True'                                           \
-            else None;                                                                  \
-        extra = (' (' + ', '.join(extra) + ')')                                         \
-            if extra                                                                    \
-            else '';                                                                    \
-        terminal = blessings.Terminal(force_styling=True);                              \
-        print(terminal.bold_yellow('Building $(building)' + extra), flush=True);        \
+    $(python) -B -c "pass;                                                         \
+        import sys;                                                                \
+        sys.exit() if '$(heading_printed)' else None;                              \
+        import re;                                                                 \
+        import blessings;                                                          \
+        extra = [];                                                                \
+        extra.append('native optimizations')                                       \
+            if '$(native_optimizations)' == 'True'                                 \
+                and '$(no_optimizations)' != 'True'                                \
+            else None;                                                             \
+        extra.append('no link time optimizations')                                 \
+            if '$(no_lto)' == 'True'                                               \
+                and '$(no_optimizations)' != 'True'                                \
+            else None;                                                             \
+        extra.append('no optimizations')                                           \
+            if '$(no_optimizations)' == 'True'                                     \
+            else None;                                                             \
+        extra.append('unsafe')                                                     \
+            if '$(unsafe_building)' == 'True'                                      \
+            else None;                                                             \
+        extra.append('serially')                                                   \
+            if re.search(r'^ *(-j|--j|--jo|--job|--jobs)=? *1$$', '$(make_jobs)')  \
+            else None;                                                             \
+        extra = (' (' + ', '.join(extra) + ')')                                    \
+            if extra                                                               \
+            else '';                                                               \
+        terminal = blessings.Terminal(force_styling=True);                         \
+        print(terminal.bold_yellow('Building modules' + extra), flush=True);       \
     "
     $(eval heading_printed = True)
     sleep 0.1
diff --git a/concept/concept b/concept/concept
--- a/concept/concept
+++ b/concept/concept
@@ -119,7 +119,21 @@ while :; do
 done
 
 # Load environment variables from the .env file
+env_backup_vars=(mpi_executor make_jobs)
+env_backup_vals=()
+for env_var in "${env_backup_vars[@]}"; do
+    eval "env_val=\"\${${env_var}}\""
+    env_backup_vals=("${env_backup_vals[@]}" "${env_val}")
+done
 source "${env_file}"
+for ((index=0; index<${#env_backup_vars[@]}; index+=1)); do
+    env_val="${env_backup_vals[${index}]}"
+    if [ -n "${env_val}" ]; then
+        env_var="${env_backup_vars[${index}]}"
+        eval "${env_var}=\"${env_val}\""
+        env_backups=("${env_backups[@]}" "${env_val}")
+    fi
+done
 
 # Add the concept directory to searched paths
 # when importing modules in Python.
@@ -500,6 +514,7 @@ local_default="False"
 main_default="${concept_dir}/main.py"
 memory_default="-1"  # -1 implies unset
 native_optimizations_default="False"
+no_lto_default="False"
 no_optimizations_default="False"
 no_recompilation_default="False"
 no_watching_default="False"
@@ -764,6 +779,12 @@ parser.add_argument(
     action='store_true',
 )
 parser.add_argument(
+    '--no-lto',
+    help='disable link time optimizations',
+    default=${no_lto_default},
+    action='store_true',
+)
+parser.add_argument(
     '--no-optimizations',
     help='disable compiler optimizations',
     default=${no_optimizations_default},
@@ -840,6 +861,7 @@ print('; '.join([
     \"walltime={}\".format(args.walltime),
     \"local={}\".format(args.local),
     \"native_optimizations={}\".format(args.native_optimizations),
+    \"no_lto={}\".format(args.no_lto),
     \"no_optimizations={}\".format(args.no_optimizations),
     \"no_recompilation={}\".format(args.no_recompilation),
     \"no_watching={}\".format(args.no_watching),
@@ -1221,17 +1243,26 @@ test:
                     rm -rf "${top_dir}/tmp" 2>/dev/null || :
                 fi
             fi
-            # Compile all the modules in parallel
+            # Compile all modules. As this process requires a lot of
+            # memory it may fail, in particular on virtual machines with
+            # dynamic memory and a small base memory. Attempting the
+            # compilation a few times in a row can help, as the dynamic
+            # memory then has a chance of increasing.
             start_time_build=$("${python}" -B -c "import time; print(time.time())")
-            exec 4>&1
-            make_output="$(
-                cd "${concept_dir}" && make                        \
+            make_concept() {
+                make                                               \
                     native_optimizations="${native_optimizations}" \
+                    no_lto="${no_lto}"                             \
                     no_optimizations="${no_optimizations}"         \
                     unsafe_building="${unsafe_building}"           \
-                    ${make_jobs}                                   \
-                    | tee >(cat >&4)                               \
-                    ; echo "concept_exit_code = ${PIPESTATUS[0]}"  \
+                    ${make_jobs}
+            }
+            exec 4>&1
+            make_output="$(
+                cd "${concept_dir}"                               \
+                && (make_concept || make_concept || make_concept) \
+                    | tee >(cat >&4)                              \
+                    ; echo "concept_exit_code = ${PIPESTATUS[0]}" \
             )"
             exec 4>&-
             exit_code="$(echo "${make_output}" | grep "concept_exit_code" \
@@ -1269,6 +1300,10 @@ if [ "${utility}" != "${utility_unspecified}" ]; then
     native_optimizations_flag=""
     if [ "${native_optimizations}" == "True" ]; then
         native_optimizations_flag="--native-optimizations"
+    fi
+    no_lto_flag=""
+    if [ "${no_lto}" == "True" ]; then
+        no_lto_flag="--no-lto"
     fi
     no_optimizations_flag=""
     if [ "${no_optimizations}" == "True" ]; then
diff --git a/installer b/installer
--- a/installer
+++ b/installer
@@ -416,10 +416,10 @@ set_version "blessings"         "1.7"
 set_version "cython"            "0.29.24"
 set_version "cythongsl"         "0.2.2"
 set_version "h5py"              "3.3.0"
-set_version "matplotlib"        "3.4.2"
-set_version "mpi4py"            "3.0.3"
-set_version "numpy"             "1.21.1"
-set_version "pip"               "21.2.3"
+set_version "matplotlib"        "3.4.3"
+set_version "mpi4py"            "3.1.1"
+set_version "numpy"             "1.21.2"
+set_version "pip"               "21.2.4"
 set_version "scipy"             "1.7.1"
 set_version "setuptools"        "57.4.0"
 set_version "sphinx"            "4.1.2"
@@ -881,8 +881,12 @@ fi
 log="${log/__top_dir__/${top_dir}}"
 # Check for another installation that is already running
 if [ "${check_other_running_installation}" != "False" ] && [ -f "${log}" ]; then
-    installpid_line="$(grep "^${status_prefix}${status_installpid}" "${log}" 2>/dev/null \
-        | tail -n 1)"
+    installpid_line=""
+    while read logline; do  # we really want to 'grep', but this migh not (yet) be installed
+        if [[ "${logline}" == "${status_prefix}${status_installpid}"* ]]; then
+            installpid_line="${logline}"
+        fi
+    done <<< "$(cat "${log}")"
     installpid_old=""
     if [ -n "${installpid_line}" ]; then
         installpid_old="${installpid_line#*=}"
@@ -2072,7 +2076,7 @@ make_jobs_set_by_user="False"
 if [ -n "${make_jobs}" ]; then
     make_jobs_set_by_user="True"
 fi
-if [ "${ssh}" == "False" ] && [ -z "${make_jobs}" ]; then
+if ([ "${ssh}" == "False" ] && [ -z "${make_jobs}" ]) || [ -n "${make_jobs}" ]; then
     make_jobs_test_dir="${top_dir}/tmp/make_jobs_test"
     rm -rf "${make_jobs_test_dir}" || :
     mkdir -p "${make_jobs_test_dir}"
@@ -2080,9 +2084,15 @@ if [ "${ssh}" == "False" ] && [ -z "${make_jobs}" ]; then
 test:
 \t@echo success
 " > "${make_jobs_test_dir}/Makefile"
-    make_jobs_output="$(cd "${make_jobs_test_dir}" && make -j 2>/dev/null)" || :
-    if [ "${make_jobs_output}" == "success" ]; then
+    if [ -z "${make_jobs}" ]; then
         make_jobs="-j"
+    fi
+    make_jobs_output="$(cd "${make_jobs_test_dir}" && make ${make_jobs} 2>/dev/null)" || :
+    if [ "${make_jobs_output}" != "success" ]; then
+        if [ "${make_jobs_set_by_user}" == "True" ]; then
+            echo "Changing make_jobs from '${make_jobs}' to ''" 2>&1
+        fi
+        make_jobs=""
     fi
     rm -rf "${make_jobs_test_dir}" || :
 fi
@@ -7018,9 +7028,10 @@ fi
 # as we need to link to OpenBLAS).
 if [ "${scipy_install}" == "True" ] && [ "${scipy_installed}" == "False" ] \
     && [ "$(check_pypackage_installed scipy)" == "False" ]; then
-    # As of SciPy 1.4, pybind11 is a required dependency, though this is
-    # not automatically installed by pip. If not already installed, we
-    # install this Python package now.
+    # As of SciPy 1.4, pybind11 is a required dependency.
+    # As of SciPy 1.7, Pythran is a required dependency.
+    # These are not automatically installed by pip.
+    # If not already installed, we install these Python packages now.
     dependencies=( \
         "pybind11" \
         "pythran"  \
@@ -7074,16 +7085,6 @@ library_dirs = ${blas_dir}/lib
 include_dirs = ${blas_dir}/include
 runtime_library_dirs = ${blas_dir}/lib
 " > "${scipy_build_dir}/site.cfg"
-    # At least in SciPy 1.4.1, compilation of SciPy may fail with an
-    # error stating that int64_t has not been declared.
-    # We fix this below.
-    rectangular_lsap="${scipy_build_dir}/scipy/optimize/rectangular_lsap/rectangular_lsap.cpp"
-    echo "
-/* Fix needed at least for SciPy 1.4.1 */
-#include \"rectangular_lsap.h\"
-
-$(cat "${rectangular_lsap}")
-" > "${rectangular_lsap}"
     cp -r "${scipy_build_dir}" "${scipy_build_dir}_cp"
     # Build and install SciPy with OpenBLAS support.
     # We wish to use the gfortran Fortran compiler. We try out all the
@@ -7112,6 +7113,10 @@ $(cat "${rectangular_lsap}")
         rm -rf "${scipy_build_dir}" || :
         cp -r "${scipy_build_dir}_cp" "${scipy_build_dir}"
         cd "${scipy_build_dir}"
+        if [ -n "${zip_safe}" ]; then
+            sed -i "s/\(^ *\)\(setup *(.*\)$/\1metadata['zip_safe'] = ${zip_safe}; \2/" \
+                setup.py || return 1
+        fi
         echo "True" > ".setuppy_success"
         if [ -n "${fcompiler}" ]; then
             ("${python}" setup.py build --fcompiler="${fcompiler}" \
@@ -7169,6 +7174,7 @@ extra_argv=['-q', '--color=yes', '-k not test_face'])" 2>&1 | tee "test_log"; \
         pyuser "" "--user"                                         ";" \
         scipy_gfortran "True" "False"                              ";" \
         compiler "${compiler_possibilities_specified_mpi_last[@]}" ";" \
+        zip_safe "False" ""                                        ";" \
         cstd "-std=c99" ""                                         ";" \
         fcompiler "gnu95" ""                                       ";" \
         extra_FCFLAGS "" "-fPIC"                                   ";" \
@@ -7650,13 +7656,13 @@ with open('${env_file}', 'w', encoding='utf-8') as file:
                 mpiexec_args="${mpiexec_args} --bind-to none"
             fi
         fi
-        sed -i "s/^mpi_executor=\"\"/mpi_executor=\"mpiexec${mpiexec_args}\"/" "${env_file}" || :
+        sed -i "s/mpi_executor=\"\"/mpi_executor=\"mpiexec${mpiexec_args}\"/" "${env_file}" || :
         reset_environment
     fi
     # If the make_jobs variable is set by the user,
     # store this in the .env file.
     if [ -n "${make_jobs}" ] && [ "${make_jobs_set_by_user}" == "True" ]; then
-        sed -i "s/^make_jobs=\"\"/make_jobs=\"${make_jobs}\"/" "${env_file}" || :
+        sed -i "s/make_jobs=\"\"/make_jobs=\"${make_jobs}\"/" "${env_file}" || :
     fi
     # Create the .paths file,
     # storing important paths used by CO𝘕CEPT.
@@ -8870,6 +8876,13 @@ fi
 ##############################
 # Testing GADGET and CO𝘕CEPT #
 ##############################
+# As the CO𝘕CEPT build process requires a lot of memory, we perform
+# the build in serial unless make_jobs is set.
+make_jobs_backup="${make_jobs}"
+if [ "${make_jobs_set_by_user}" == "False" ]; then
+    make_jobs="-j 1"
+fi
+export make_jobs="${make_jobs}"
 if [ "${concept_install}" == "True" ] && [ "${concept_installed}" == "False" ]; then
     if [ "${do_tests}" == "True" ]; then
         # Run basic CO𝘕CEPT test to test the environment
@@ -8932,6 +8945,7 @@ if [ "${concept_install}" == "True" ] && [ "${concept_installed}" == "False" ]; 
     # to minimize the number of files in the CO𝘕CEPT directory.
     install_notice "CONCEPT" "${gadget_dir}"
 fi
+export make_jobs="${make_jobs_backup}"
 
 
 
@@ -8944,9 +8958,30 @@ if [ "${concept_install}" == "True" ] && [ "${concept_installed}" == "False" ]; 
     # as the CO𝘕CEPT build process does this by itself.
     echo
     set_status "Building ${esc_concept}"
-    # Build the code by running it with no parameters specified
+    # Build the code by running it with no parameters specified.
+    # As the CO𝘕CEPT build process requires a lot of memory, we perform
+    # the build in serial unless make_jobs is set.
+    # On failure we try again without link time optimizations.
+    make_jobs_backup="${make_jobs}"
+    if [ "${make_jobs_set_by_user}" == "False" ]; then
+        make_jobs="-j 1"
+    fi
+    export make_jobs="${make_jobs}"
     cd "${concept_dir}"
-    logo_printed=True "${concept}" --local 2>&1
+    build_concept_success="True"
+    logo_printed=True "${concept}" --local 2>&1 || build_concept_success="False"
+    if [ "${build_concept_success}" == "False" ]; then
+        error "Failed to build ${esc_concept}"
+        echo "Will now try without link time optimizations"
+        (source "${concept}" && make clean) || :
+        build_concept_success="True"
+        logo_printed=True "${concept}" --local --no-lto 2>&1 || build_concept_success="False"
+    fi
+    export make_jobs="${make_jobs_backup}"
+    if [ "${build_concept_success}" == "False" ]; then
+        error "Failed to build ${esc_concept} even with no link time optimizations"
+        exit 1
+    fi
     # Remove log and parameter copy file generated by the above run
     (source "${concept}" && make clean_logs clean_params_cp) || :
     # Remove compilation artefacts if installing in slim mode
