added the update utility

diff --git a/concept/run b/concept/run
--- a/concept/run
+++ b/concept/run
@@ -1,30 +1,30 @@
 #!/usr/bin/env bash
 
-# This file is part of CONCEPT, the cosmological N-body code in Python.
-# Copyright (C) 2015 Jeppe Mosgard Dakin.
+# This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
+# Copyright © 2015 Jeppe Mosgaard Dakin.
 #
-# CONCEPT is free software: you can redistribute it and/or modify
+# CO𝘕CEPT is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
-# CONCEPT is distributed in the hope that it will be useful,
+# CO𝘕CEPT is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
-# along with CONCEPT. If not, see http://www.gnu.org/licenses/
+# along with CO𝘕CEPT. If not, see http://www.gnu.org/licenses/
 #
-# The auther of CONCEPT can be contacted at
+# The auther of CO𝘕CEPT can be contacted at
 # jeppe.mosgaard.dakin(at)post.au.dk
-# The latest version of CONCEPT is available at
+# The latest version of CO𝘕CEPT is available at
 # https://github.com/jmd-dk/concept/
 
 
 
-# This script runs the CONCEPT code.
-# Run the script with the -h option to get help
+# This script runs the CO𝘕CEPT code.
+# Run the script with the -h option to get help.
 
 # If this file is being sourced, backups of 'this_file' and 'this_dir'
 # is needed not to alter the values of these variables.
@@ -63,7 +63,8 @@ terminal_CONCEPT="CO${esc_italic}N${esc_no_italic}CEPT"
 colorprint()
 {
 # Arguments: Message, color
-${python} -B -c "import sys
+"${python}" -B -c "
+import sys
 from blessings import Terminal
 terminal = Terminal(force_styling=True)
 msg='${1}'.replace('CONCEPT', '${terminal_CONCEPT}')
@@ -93,16 +94,25 @@ if [ "${BASH_SOURCE[0]}" != "${0}" ]; then
 fi
 
 # Default values of command-line arguments
-nprocs=1
-params="None"  #"${this_dir}/params/default"
-main="${concept_dir}/main.py"
-pure_python=0
-walltime=72
+local_default="False"
+main_default="${concept_dir}/main.py"
+nprocs_default=1
+params_default="None"
+pure_python_default="False"
+walltime_default=72
 # List of remote queues and number of CPU per node. The first queue is the default queue 
 queues=(q8n q8 q4)
 ppns=(8 8 4)
 # Should PBS be used to submit remote jobs?
 use_PBS=1
+
+# Initial but illegal values of some command-line arguments,
+# for testing whether these arguments have been supplied.
+nprocs_unspecified="-1"
+params_unspecified="__none__"
+queue_unspecified="__none__"
+test_unspecified="__none__"
+util_unspecified="__none__"
 
 # Change to the concept code directory
 cd "${concept_dir}"
@@ -110,103 +120,94 @@ cd "${concept_dir}"
 # library. To fix this we export the zlib library at run time.
 export LD_LIBRARY_PATH="${zlib_dir}/lib:${LD_LIBRARY_PATH}"
 
-# Use Python's argparse module to handle command line arguments
-args=($(${python} -B -c "
-import argparse
-import sys
-from os.path import basename, dirname
-# Enables Python to write directly to screen when asked for help
-help_req = False
-if any(h in sys.argv for h in ['-h', '--he', '--hel', '--help']):
-    sys.stdout = sys.stderr
-    help_req = True
-# Set the filename of the script
-sys.argv[0] = '${this_file}'
+# Use Python's argparse module to handle command-line arguments
+args=($("${python}" -B -c "
+import argparse, sys
 # Setup command-line arguments
-parser = argparse.ArgumentParser(description='Run the CONCEPT code.')
-parser.add_argument('--local',
-                    help='Force the run to be done locally, without submitting it via PBS',
-                    default=False,
-		            action='store_true',
-                    )
+parser = argparse.ArgumentParser(prog='$(basename ${this_file})',
+                                 description='Run the CONCEPT code')
 parser.add_argument('-m', '--main',
                     help='entry point of the code',
-                    default='${main}',
+                    default='${main_default}',
                     )
 parser.add_argument('-n', '--nprocs',
                     help='number of processes',
                     type=int,
-                    default=${nprocs},
+                    default=${nprocs_unspecified},
                     )
 parser.add_argument('-p', '--params',
                     help='parameterfile to use',
-                    default='${params}',
-                    )
-parser.add_argument('--pure-python',
-                    help='run in pure Python mode',
-                    default=${pure_python},
-                    action='store_true',
-                    )
-parser.add_argument('-t', '--test',
-                    help='run test TEST. TEST can be any subdirectory of the tests directory. Use TEST=all to run all tests',
-                    default='none',
+                    default='${params_unspecified}',
                     )
 parser.add_argument('-q', '--queue',
                     help='Queue for submission of the remote job. If omitted the script will try to choose the best.',
-                    default='none',
+                    default='${queue_unspecified}',
+                    )
+parser.add_argument('-t', '--test',
+                    help='run test TEST. TEST can be any subdirectory of the tests directory. Use TEST=all to run all tests',
+                    default='${test_unspecified}',
+                    )
+parser.add_argument('-u', '--util',
+                    nargs='+',
+                    help='run utility UTIL. UTIL can be any executable in the utilities directory',
+                    default=['${util_unspecified}'],
                     )
 parser.add_argument('-w', '--walltime',
                      help='Set the PBS walltime in whole hours',
                      type=int,
-                     default=${walltime},
+                     default=${walltime_default},
                      )
+parser.add_argument('--local',
+                    help='Force the run to be done locally, without submitting it via PBS',
+                    default=${local_default},
+                    action='store_true',
+                    )
+parser.add_argument('--pure-python',
+                    help='run in pure Python mode',
+                    default=${pure_python_default},
+                    action='store_true',
+                    )
+# Enables Python to write directly to screen (stderr)
+# in case of help request
+stdout_copy = sys.stdout
+sys.stdout = sys.stderr
+# Now do the actual argument parsing, including writing out the help message
 args = parser.parse_args()
-# Warnings when basic parameters are not supplied
-unspecified_nprocs = False
-unspecified_params = False
-arg = '--nprocs'
-if not any(n in sys.argv for n in ['-n'] + [arg[:i] for i in range(4, len(arg) + 1)]):
-    unspecified_nprocs = True
-arg = '--params'
-if not any(p in sys.argv for p in ['-p'] + [arg[:i] for i in range(4, len(arg) + 1)]):
-    if basename(dirname(args.main)) == 'tests':
-        # Running a test but no parameterfile specified!
-        args.params = dirname(args.main) + '/params_' + basename(args.main)
-    else:
-        unspecified_params = True
+# Reset stdout
+sys.stdout = stdout_copy
 # Print out the arguments.
 # These will be captured in the bash 'args' variable
-print(int(help_req),
+print('graceful_exit',
+      args.main,
       args.nprocs,
       args.params,
-      args.main,
-      int(args.pure_python),
-      int(unspecified_nprocs),
-      int(unspecified_params),
-      args.test,
-      args.walltime,
       args.queue,
-      int(args.local),
+      args.test,
+      args.util[0],
+      '\"' + '\"__space__\"'.join(args.util[1:]).replace(' ','__space__') + '\"' if len(args.util) > 1 else '\"\"',
+      args.walltime,
+      args.local,
+      args.pure_python,
       )
 " "$@"))
-help_req="${args[0]}"
-nprocs="${args[1]}"
-params="${args[2]}"
-main="${args[3]}"
-pure_python="${args[4]}"
-unspecified_nprocs="${args[5]}"
-unspecified_params="${args[6]}"
-test="${args[7]}"
+graceful_exit="${args[0]}"
+main="${args[1]}"
+nprocs="${args[2]}"
+params="${args[3]}"
+queue="${args[4]}"
+test="${args[5]}"
+util="${args[6]}"
+util_args="${args[7]//__space__/ }"
 walltime="${args[8]}"
-queue="${args[9]}"
-local="${args[10]}"
-if [ -z "${help_req}" ] || [ "${help_req}" == 1 ]; then
+local="${args[9]}"
+pure_python="${args[10]}"
+if [ -z "${graceful_exit}" ]; then
     # Help requested and given. Exit
     trap : 0
     exit 0
 fi
 if [ "${#args[@]}" -ne 11 ]; then
-    colorprint "Error: Not every command line argument was gracefully dealt with!" "red"
+    colorprint "Error: Not every command-line argument was gracefully dealt with!" "red"
     exit 1
 fi
 
@@ -226,30 +227,57 @@ trap 'abort' EXIT
 set -e
 
 # Convert all supplied paths to absolute paths
-params="$(absolute "${params}")"
 main="$(absolute "${main}")"
-if [ "${test}" != "none" ] && [ "${test}" != "all" ]; then
+if [ "${params}" != "${params_unspecified}" ]; then
+    params="$(absolute "${params}")"
+fi
+if [ "${test}" != "${test_unspecified}" ] && [ "${test}" != "all" ]; then
     test="${concept_dir}/tests/$(basename "${test}")"
 fi
-
-# Do the parameterfile, the main file and the test file exist?
-if [ "${unspecified_params}" == 0 ] && [ ! -f "${params}" ]; then
-    colorprint "Error: Parameterfile \"${params}\" does not exist!" "red"
-    exit 1
+if [ "${util}" != "${util_unspecified}" ]; then
+    util="${concept_dir}/utilities/$(basename "${util}")"
 fi
+
+# Do the supplied paths exist?
 if [ ! -f "${main}" ]; then
     colorprint "Error: Entry point \"${main}\" does not exist!" "red"
     exit 1
 fi
-if [ "${test}" != "none" ] && [ "${test}" != "all" ] && [ ! -d "${test}" ]; then
+if [ "${params}" != "${params_unspecified}" ] && [ ! -f "${params}" ]; then
+    colorprint "Error: Parameterfile \"${params}\" does not exist!" "red"
+    exit 1
+fi
+if [ "${test}" != "${test_unspecified}" ] && [ "${test}" != "all" ] && [ ! -d "${test}" ]; then
     colorprint "Error: Test \"${test}\" does not exist!" "red"
     exit 1
 fi
+if [ "${util}" != "${util_unspecified}" ] && [ ! -f "${util}" ]; then
+    colorprint "Error: Utility \"${util}\" does not exist!" "red"
+    exit 1
+fi
+
+# Assigned values to unspecified parameters
+running_test_or_util="False"
+if [ "${util}" != "${util_unspecified}" ] || [ "${test}" != "${test_unspecified}" ]; then
+    running_test_or_util="True"
+fi
+if [ "${nprocs}" == "${nprocs_unspecified}" ]; then
+    nprocs="${nprocs_default}"
+    if [ "${running_test_or_util}" == "False" ]; then
+        echo "Number of processes not specified - Will use ${nprocs}"
+    fi
+fi
+if [ "${params}" == "${params_unspecified}" ]; then
+    params="${params_default}"
+    if [ "${running_test_or_util}" == "False" ]; then
+        echo "Parameterfile not specified - Will use default parameters"
+    fi
+fi
 
 # If a test is to be run, run it and exit
-if [ "${test}" != "none" ]; then
-    trap : 0
+if [ "${test}" != "${test_unspecified}" ]; then
     if [ "${test}" == "all" ]; then
+        trap : 0
         for dir in "${concept_dir}/tests/"*/; do
             dir=${dir%*/}
             colorprint "\nRunning $(basename ${dir}) test" "yellow"
@@ -258,22 +286,34 @@ if [ "${test}" != "none" ]; then
         colorprint "All tests ran successfully" "green"
     else
         colorprint "Running $(basename ${test}) test" "yellow"
+        trap : 0
         "${test}/run_test"
     fi
+    exit 0
+fi
+
+# If a utility is to be run, run it and exit
+if [ "${util}" != "${util_unspecified}" ]; then
+    # Export every command-line argument. These will be fed back into
+    # this script when called from the utility.
+    export main="${main}"
+    export nprocs="${nprocs}"
+    export params="${params}"
+    export queue="${queue}"
+    export test="${test}"
+    export util="${util}"
+    export walltime="${walltime}"
+    export local="${local}"
+    export pure_python="${pure_python}"
+    colorprint "Running the $(basename ${util}) utility" "yellow"
+    trap : 0
+    eval "${util}" ${util_args}
     exit 0
 fi
 
 # Relative path to the main and parameter, for clean printout
 main_rel=$(${python}   -B -c "from os.path import relpath; rel = relpath('${main}',   '${concept_dir}'); print(rel if not rel.startswith('../../') else '${main}')")
 params_rel=$(${python} -B -c "from os.path import relpath; rel = relpath('${params}', '${concept_dir}'); print(rel if not rel.startswith('../../') else '${params}')")
-
-# Printout assigned values for unspecified parameters
-if [ "${unspecified_nprocs}" == 1 ]; then
-    echo "Number of processes not specified - Will use ${nprocs}"
-fi
-if [ "${unspecified_params}" == 1 ]; then
-    echo "Parameterfile not specified - Will use default parameters"
-fi
 
 # Prompt the user for the secure shell password,
 # if the live render should be uploaded to a remote host.
@@ -344,17 +384,17 @@ if [ "${scp_success}" != "success" ]; then
 fi
 
 # Compile or do cleanup from last compilation
-if [ "${pure_python}" -eq 0 ] ; then
+if [ "${pure_python}" == "True" ] ; then
+    # Rename compiled Cython modules *.so to *.so_
+    if ls "${concept_dir}/"*.so > /dev/null 2>&1; then
+        (cd "${concept_dir}" && for f in *.so; do mv "${f}" "${f%.so}.so_"; done)
+    fi
+else
     # Rename compiled Cython modules *.so_ back to *.so and compile with Cython
     if ls "${concept_dir}/"*.so_ > /dev/null 2>&1; then
         (cd "${concept_dir}" && for f in *.so_; do mv "${f}" "${f%.so_}.so"; done)
     fi
     (cd "${concept_dir}" && make)
-else
-    # Rename compiled Cython modules *.so to *.so_
-    if ls "${concept_dir}/"*.so > /dev/null 2>&1; then
-        (cd "${concept_dir}" && for f in *.so; do mv "${f}" "${f%.so}.so_"; done)
-    fi
 fi
 
 # Create the logs dir if it does not exist
@@ -362,7 +402,7 @@ mkdir -p "${concept_dir}/logs"
 
 # Determine whether this script is run locally or remotely via ssh.
 # Always treat tests as if they were run locally.
-if [ "${local}" == 0 ] && [ "${test}" == "none" ] && ([ -n "${SSH_CLIENT}" ] || [ -n "${SSH_TTY}" ]); then
+if [ "${local}" == "False" ] && [ "${test}" == "${test_unspecified}" ] && ([ -n "${SSH_CLIENT}" ] || [ -n "${SSH_TTY}" ]); then
     remote=1
 else
     remote=0
@@ -376,7 +416,7 @@ if [ "${use_PBS}" -eq 0 ] && [ "${remote}" -eq 1 ]; then
 elif [ "${use_PBS}" -eq 1 ] && [ "${remote}" -eq 1 ]; then
     # Run remotely.
     # If no queue is explicitly chosen, use one with enough free nodes
-    if [ "${queue}" == "none" ]; then
+    if [ "${queue}" == "${queue_unspecified}" ]; then
         # The first queue in the list is the default queue
         queue="${queues[0]}"
         ppn="${ppns[0]}"
@@ -402,7 +442,7 @@ elif [ "${use_PBS}" -eq 1 ] && [ "${remote}" -eq 1 ]; then
     fi
     # Check that the chosen queue can be run with all the node's CPUs in use
     if [ "$((${nprocs} % ${ppn}))" != 0 ]; then
-        colorprint "Job submission refused:\nNo queue has the right amount of processors per node" "red"
+        colorprint "Error: Job submission refused:\nNo queue has the right amount of processors per node" "red"
         exit 1
     fi
     nodes="$((${nprocs} / ${ppn}))"
@@ -425,10 +465,10 @@ cd \"${concept_dir}/logs\"
 source \"${this_file}\"
 
 # Print start messages
-if [ ${pure_python} -eq 0 ]; then
-    colorprint \"Running CONCEPT remotely on \$(hostname -f) as job \${jobid}\" \"yellow\" > \"${concept_dir}/logs/\${jobid}\"
-else
+if [ \"${pure_python}\" == \"True\" ]; then
     colorprint \"Running CONCEPT in pure Python mode remotely on \$(hostname -f) as job \${jobid}\" \"yellow\" > \"${concept_dir}/logs/\${jobid}\"
+else
+    colorprint \"Running CONCEPT remotely on \$(hostname -f) as job \${jobid}\" \"yellow\" > \"${concept_dir}/logs/\${jobid}\"
 fi
 echo \"Entry point:   \\\"${main_rel}\\\"\"    >> \"${concept_dir}/logs/\${jobid}\"
 echo \"Parameterfile: \\\"${params_rel}\\\"\"  >> \"${concept_dir}/logs/\${jobid}\"
@@ -436,14 +476,14 @@ echo \"Logfile:       \\\"logs/\${jobid}\\\"\" >> \"${concept_dir}/logs/\${jobid
 echo \"Nr. of CPUs:    ${nprocs}\"             >> \"${concept_dir}/logs/\${jobid}\"
 
 # Prepare Python options
-if [ \"${pure_python}\" == \"0\" ]; then
-    # Run as compiled library module
-    main_as_library=\"$(basename "${main%.*}.so")\"
-    m_flag=\"-m\"
-else
+if [ \"${pure_python}\" == \"True\" ]; then
     # Run as normal Python script
     main_as_library=\"${main}\"
     m_flag=\"\"
+else
+    # Run as compiled library module
+    main_as_library=\"$(basename "${main%.*}.so")\"
+    m_flag=\"-m\"
 fi
 
 # Run the code. Both stdout and stderr are being logged to logs/jobid,
@@ -480,34 +520,30 @@ else
     done
     # Print start message
     echo
-    if [ "${pure_python}" -eq 0 ]; then
-        colorprint "Running CONCEPT" "yellow" | tee "${concept_dir}/logs/${jobid}"
-    else
+    if [ "${pure_python}" == "True" ]; then
         colorprint "Running CONCEPT in pure Python mode" "yellow" | tee "${concept_dir}/logs/${jobid}"
+    else
+        colorprint "Running CONCEPT" "yellow" | tee "${concept_dir}/logs/${jobid}"
     fi
     echo "Entry point:   \"${main_rel}\""   | tee -a "${concept_dir}/logs/${jobid}"
-    if [ "${unspecified_params}" == 1 ]; then
-        echo "Parameterfile: None" | tee -a "${concept_dir}/logs/${jobid}"
-    else
-        echo "Parameterfile: \"${params_rel}\"" | tee -a "${concept_dir}/logs/${jobid}"
-    fi
+    echo "Parameterfile: \"${params_rel}\"" | tee -a "${concept_dir}/logs/${jobid}"
     echo "Logfile:       \"logs/${jobid}\"" | tee -a "${concept_dir}/logs/${jobid}"
     echo "Nr. of CPUs:    ${nprocs}"        | tee -a "${concept_dir}/logs/${jobid}"
     # Prepare Python options
-    if [ "${pure_python}" -eq 0 ] ; then
-        # Run as compiled library module
-        main_as_library="$(basename "${main%.*}.so")"
-        m_flag="-m"
-    else
+    if [ "${pure_python}" == "True" ] ; then
         # Run as normal Python script
         main_as_library="${main}"
         m_flag=""
+    else
+        # Run as compiled library module
+        main_as_library="$(basename "${main%.*}.so")"
+        m_flag="-m"
     fi
     # Run the code. Print stdout and stderr to the terminal while at the
     # same time logging them to logs/jobid. The stderr alone is also
     # logged to logs/jobid_err.
     "${mpiexec}" -n "${nprocs}" "${python}" -B ${m_flag} "${main_as_library}" "params='${params}'" "scp_password='${scp_password}'" 2> >(tee -a "${concept_dir}/logs/${jobid}_err") | tee -a "${concept_dir}/logs/${jobid}"
-    # Get exit status of the above CONCEPT run
+    # Get exit status of the above CO𝘕CEPT run
     concept_exit_status="${PIPESTATUS[0]}"
     # Run complete. Remove error log if empty
     if [ -f "${concept_dir}/logs/${jobid}_err" ] && [ ! -s "${concept_dir}/logs/${jobid}_err" ]; then
@@ -517,7 +553,7 @@ else
         colorprint "Check the following error log for more information:" "red" 2>&1 | tee -a "${concept_dir}/logs/${jobid}"
         colorprint "\"${concept_dir}/logs/${jobid}_err\"" "red" 2>&1 | tee -a "${concept_dir}/logs/${jobid}"
     fi
-    # If the CONCEPT run exited erroneously, exit now
+    # If the CO𝘕CEPT run exited erroneously, exit now
     if [ "${concept_exit_status}" != "0" ]; then
         exit 1
     fi
