added support for PBS

diff --git a/concept/run b/concept/run
--- a/concept/run
+++ b/concept/run
@@ -23,10 +23,15 @@ while [ 1 ]; do
 done
 
 # Default values of command-line arguments
+walltime=24
 nprocs=1
 params="${this_dir}/params/default"
 main="${this_dir}/main.py"
 pure_python=0
+
+# List of remote queues and number of CPU per node. The first queue is the default queue. 
+queues=(q8n q8 q4)
+ppns=(8 8 4)
 
 # Use Python's argparse module to handle command-line arguments
 args=(`${python} -B -c "
@@ -40,28 +45,37 @@ if any(h in sys.argv for h in ['-h', '--he', '--hel', '--help']):
 sys.argv[0] = '${this_file}'
 # Setup command-line arguments
 parser = argparse.ArgumentParser(description='Run the CONCEPT code.')
+parser.add_argument('-e', '--exit',
+                    help='exit as soon as all auxiliary files have been created',
+                    default=False,
+                    action='store_true',
+                    )
+parser.add_argument('-w', '--walltime',
+                    help='Set the PBS walltime in whole hours',
+                    type=int,
+                    default=${walltime},
+                    )
+parser.add_argument('-m', '--main',
+                    help='entry point of the code',
+                    default='${main}',
+                    )
 parser.add_argument('-n', '--nprocs',
-                    help='Number of processes.',
+                    help='number of processes',
                     type=int,
                     default=${nprocs},
                     )
 parser.add_argument('-p', '--params',
-                    help='Parameterfile to use',
+                    help='parameterfile to use',
                     default='${params}',
                     )
-parser.add_argument('-m', '--main',
-                    help='Entry point of the code',
-                    default='${main}',
-                    )
 parser.add_argument('--pure-python',
-                    help='Run in pure Python mode',
+                    help='run in pure Python mode',
                     default=${pure_python},
                     action='store_true',
                     )
-parser.add_argument('--exit',
-                    help='Exit as soon as all auxiliary files have been created',
-                    default=False,
-                    action='store_true',
+parser.add_argument('-t', '--test',
+                    help='run test TEST. TEST can be any subdirectory of the tests directory. Use TEST=all to run all tests.',
+                    default='none',
                     )
 args = parser.parse_args()
 # Warnings when basic parameters are not supplied
@@ -86,6 +100,8 @@ print(args.nprocs,
       int(unspecified_nprocs),
       int(unspecified_params),
       int(args.exit),
+      args.test,
+      args.walltime,
       )
 " "$@"`)
 nprocs="${args[0]}"
@@ -95,7 +111,9 @@ pure_python="${args[3]}"
 unspecified_nprocs="${args[4]}"
 unspecified_params="${args[5]}"
 exit="${args[6]}"
-if [ "${#args[@]}" -ne 7 ]; then
+test="${args[7]}"
+walltime="${args[8]}"
+if [ "${#args[@]}" -ne 9 ]; then
     exit 1
 fi
 
@@ -115,7 +133,7 @@ trap 'abort' EXIT
 set -e
 
 # Convert all supplied paths to absolute paths
-absolutee()
+absolute()
 {
     local path="${1}"
     path="${path//[ ]/\\ }"        # Places backslashes before spaces. These are needed when expanding tilde, but they will not persist!
@@ -123,33 +141,13 @@ absolutee()
     path=$(readlink -f "${path}")  # Convert to absolute path
     echo "${path}"
 } 
-params=$(absolutee "${params}")
-main=$(absolutee "${main}")
-
-# Print warnings for unspecified parameters
-if [ "${unspecified_nprocs}" == 1 ]; then
-    echo "Number of processes not specified - Will use ${nprocs}"
-fi
-if [ "${unspecified_params}" == 1 ]; then
-    echo "Parameterfile not specified - Will use ${params}"
+params="$(absolute "${params}")"
+main="$(absolute "${main}")"
+if [ "${test}" != "none" ] && [ "${test}" != "all" ]; then
+    test="${this_dir}/tests/$(basename "${test}")"
 fi
 
-# Is nprocs a power of 2?
-legal_nprocs=`"${python}" -B -c "
-from numpy import log2
-exponent = log2(${nprocs})
-if exponent == int(exponent):
-    legal_nprocs = 1
-else:
-    legal_nprocs = 0
-print(legal_nprocs)
-"`
-if [ "${legal_nprocs}" -eq 0 ]; then
-    echo "Error: Number of processes (${nprocs}) is not a power of 2!"
-    #exit 1
-fi
-
-# Do the parameterfile and the main file exist?
+# Do the parameterfile, the main file and the test file exist?
 if [ ! -f "${params}" ]; then
     echo "Error: "${params}" does not exist!"
     exit 1
@@ -157,6 +155,38 @@ fi
 if [ ! -f "${main}" ]; then
     echo "Error: "${main}" does not exist!"
     exit 1
+fi
+if [ "${test}" != "none" ] && [ "${test}" != "all" ]; then
+    if [ ! -d "${test}" ]; then
+        echo "Error: "${test}" does not exist!"
+        exit 1
+    fi
+fi
+
+# If a test is to be run, run it and exit
+if [ "${test}" != "none" ]; then
+    trap : 0
+    if [ "${test}" == "all" ]; then
+        for dir in "${this_dir}/tests/"*/
+        do
+            dir=${dir%*/}
+           printf "\e[1m\e[93mRunning $(basename ${dir}) test\e[0m\n"
+           "${dir}/run_test"
+        done
+        printf "\e[1m\e[92mAll tests ran successfully\e[0m\n"
+    else
+        printf "\e[1m\e[93mRunning $(basename ${test}) test\e[0m\n"
+        "${test}/run_test"
+    fi
+    exit 0
+fi
+
+# Print warnings for unspecified parameters
+if [ "${unspecified_nprocs}" == 1 ]; then
+    echo "Number of processes not specified - Will use ${nprocs}"
+fi
+if [ "${unspecified_params}" == 1 ]; then
+    echo "Parameterfile not specified - Will use ${params}"
 fi
 
 # Compile or do cleanup from last compilation
@@ -217,19 +247,73 @@ print(password)
 " "$@"`)
 password="${args[0]}"
 
-# Run the code. Note that password and whether to exit is passed as arguments
-if [ "${pure_python}" -eq 0 ] ; then
-    printf "\n\e[1m\e[93mRunning CO\e[3mN\e[0m\e[1m\e[93mCEPT\e[0m\n"
+# Determine whether this script is run locally or remotely via ssh
+if [ -n "${SSH_CLIENT}" ] || [ -n "${SSH_TTY}" ]; then
+    remote=1
 else
-    printf "\n\e[1m\e[93mRunning CO\e[3mN\e[0m\e[1m\e[93mCEPT in pure Python mode\e[0m\n"
+    remote=0
 fi
-echo "Entry point:   ${main}"
-echo "Parameterfile: ${params}"
-echo "Nr. of CPUs:   ${nprocs}"
+
+# Run the code. Note that password and whether to exit is passed as arguments
+mkdir -p "${this_dir}/logs"
 cd "${this_dir}"
-"${mpiexec}" -n "${nprocs}" --prefix "${openmpi_dir}" "${python}" -B "${main}" "${password}" "${exit}"
+if [ ${remote} -eq 1 ]; then
+    # The first queue in the list is the default queue
+    queue="${queues[0]}"
+    ppn="${ppns[0]}"
+    # Change to the queue that has enogh free CPUS to begin job immediately
+    node_table=$(nodes)
+    for i in $(eval echo "{0..${#queues[@]}}" | sed s/'\w*$'//)
+    do
+        free_nodes=$(echo "${node_table}" | grep -o -P "(?<= ${queues[${i}]}:).*(?= free)" | awk '{print $NF}')
+        free_cpus=$(echo "$((${free_nodes} * ${ppns[${i}]}))")
+        if [ "${free_cpus}" -ge "${nprocs}" ] && [ "$((${nprocs} % ${ppns[${i}]}))" -eq 0 ]; then
+            queue="${queues[${i}]}"
+            ppn="${ppns[${i}]}"
+            break
+        fi
+    done
+    # Check that the chosen queue can be run with all the node's cpu's in use
+    if [ "$((${nprocs} % ${ppn}))" != 0 ]; then
+        printf "\e[1m\e[91mJob submition refused:\nNo queue has the right amount of processors per node\e[0m\n" >&2
+        exit 1
+    fi
+    nodes="$((${nprocs} / ${ppn}))"
+    # Write a jobscript file
+    echo -e "#!/bin/bash
+
+#PBS -q ${queue}
+#PBS -l nodes=${nodes}:ppn=${ppn}
+#PBS -N $(whoami):CONCEPT
+#PBS -l walltime=${walltime}:00:00
+#PBS -m abe
+#PBS -j oe
+
+# Get the id of the current job
+env | grep PBS
+jobid=\"\${PBS_JOBID%.in1}\"
+
+cd \"\${PBS_O_WORKDIR}\"
+
+# Run
+\"${mpiexec}\" --prefix \"${openmpi_dir}\" \"${python}\" -B \"${main}\" \"${password}\" \"${exit}\" > \"${this_dir}/logs/remote_\${jobid}\"
+" > "${this_dir}/jobscript"
+
+    # Submit the remote job
+    qsub "${jobscript}"
+else
+    # Run locally
+    if [ "${pure_python}" -eq 0 ] ; then
+        printf "\n\e[1m\e[93mRunning CO\e[3mN\e[0m\e[1m\e[93mCEPT\e[0m\n"
+    else
+        printf "\n\e[1m\e[93mRunning CO\e[3mN\e[0m\e[1m\e[93mCEPT in pure Python mode\e[0m\n"
+    fi
+    echo "Entry point:   ${main}"
+    echo "Parameterfile: ${params}"
+    echo "Nr. of CPUs:   ${nprocs}"
+    "${mpiexec}" -n "${nprocs}" --prefix "${openmpi_dir}" "${python}" -B "${main}" "${password}" "${exit}"
+fi
 
 # Run complete. Deactivate trap before exiting.
 trap : 0
-printf "\e[1m\e[92mCO\e[3mN\e[0m\e[1m\e[92mCEPT ran successfully\e[0m\n"
 
