polished utilities for use on clusters

diff --git a/concept/utilities/render3D b/concept/utilities/render3D
--- a/concept/utilities/render3D
+++ b/concept/utilities/render3D
@@ -40,15 +40,14 @@ this_dir="$(dirname "${this_file}")"
 source "${this_dir}/../concept"
 
 # Set up error trapping
-ctrl_c()
-{
+ctrl_c(){
     trap : 0
     exit 2
 }
-abort()
-{
+abort(){
+    exit_code=$?
     colorprint "An error occurred while using the \"$(basename "${this_file}")\" utility!" "red"
-    exit 1
+    exit ${exit_code}
 }
 if [ "${called_from_concept}" == "True" ]; then
     trap 'ctrl_c' SIGINT
@@ -176,57 +175,83 @@ paths['params'] = params_path_ori
 " > "${params_filename}"
     # Cleanup
     rm -f "${snapshot_params_filename}"
-    # Function that calls the concept script with appropriate arguments.
-    # Note that the submitted jobs should not be watched at this time.
-    call_concept()
-    {
-        "${concept}" -m "${main}"            \
-                     -n  ${nprocs}           \
-                     -p "${params_filename}" \
-                     -q "${queue}"           \
-                     -w "${walltime}"        \
-                     ${interactive_flag}     \
-                     ${local_flag}           \
-                     ${no_optimization_flag} \
-                     --no-watch              \
-                     ${pure_python_flag}     \
-                     ${unsafe_build_flag}
-    }
-    # Run CO𝘕CEPT to produce the 3D render
-    if [ "${remote}" == "True" ]; then
-        concept_output="$(call_concept)"
-        echo "${concept_output}"
-        # Get jobid
-        jobid="$(echo "${concept_output}" | grep "Job .* submitted to queue" 2>/dev/null || :)"
-        if [ -n "${jobid}" ]; then
-            jobid="$(echo "${jobid}" | awk '{print $2}')"
-            jobids=("${jobids[@]}" "${jobid}")
-        fi
-    elif [ "${remote}" == "False" ]; then
-        call_concept
-    else
-        colorprint "Variable \"remote\" not properly set" "red"
+    # Run CO𝘕CEPT to produce the 3D render.
+    # Submitted jobs should not be watched at this time.
+    # Capture the jobid and exit code.
+    exec 4>&1
+    jobid_and_exit_code="$(                \
+        "${concept}"                       \
+            -m "${main}"                   \
+            -n  ${nprocs}                  \
+            -p "${params_filename}"        \
+            -q "${queue}"                  \
+            -w "${walltime}"               \
+            --memory ${memory}             \
+            ${interactive_flag}            \
+            ${local_flag}                  \
+            ${no_optimization_flag}        \
+            --no-watch                     \
+            ${pure_python_flag}            \
+            ${unsafe_build_flag}           \
+        | tee >(cat  >&4)                  \
+        | grep "^Log file: \|^Job "        \
+        | head -n 1                        \
+        ; echo "exit_code${PIPESTATUS[0]}" \
+    )"
+    exec 4>&-
+    exit_code="$("${python}" -B -c                                                              \
+        "import re; print(re.search(r'exit_code(\d+)', '''${jobid_and_exit_code}''').group(1))" \
+        2>/dev/null)" || :
+    if [ -z "${exit_code}" ]; then
+        colorprint "Error capturing exit code" "red"
         exit 1
+    elif [ ${exit_code} != 0 ]; then
+        exit ${exit_code}
     fi
+    jobid="$("${python}" -B -c                                                                  \
+        "import re; print(re.search(r'(/|^Job )(\d+)', '''${jobid_and_exit_code}''').group(2))" \
+        2>/dev/null)" || :
+    jobids=("${jobids[@]}" "${jobid}")
+
 done
 
 # Deactivate traps before exiting
 trap : 0
 
 # Watch remotely submitted jobs in submission order
-if [ ${#jobids[@]} -gt 0 ] && [ "${no_watch}" == "False" ]; then
-    if [ ${#jobids[@]} -gt 1 ]; then
-        printf "\nYou can now kill (Ctrl-C) this script without cancelling the jobs\n"
-        printf "\nWill now watch the submitted jobs\n\n"
-    else
-        printf "\nYou can now kill (Ctrl-C) this script without cancelling the job\n"
-        printf "\nWill now watch the submitted job\n\n"
-    fi
+plural=""
+if [ ${N_snapshots} -gt 1 ]; then
+    plural="s"
+fi
+if [ "${remote}" == "True" ] && [ "${no_watch}" == "False" ]; then
+    printf "\nYou can now kill (Ctrl-C) this script without cancelling the job${plural}\n"
+    printf "\nWill now watch the submitted job${plural}\n\n"
     for jobid in "${jobids[@]}"; do
         "${concept}" -u watch ${jobid}
         echo
     done
+else
+    echo
 fi
 
 # Exit gracefully
-colorprint "$(basename "${this_file}") utility ran successfully" "green"
+if [ "${remote}" == "False" ] || [ "${no_watch}" == "False" ]; then
+    completely_successful="yes"
+    for jobid in "${jobids[@]}"; do
+        if [ -z "${jobid}" ]; then
+            colorprint "Error capturing jobid from output" "red"
+            exit 1
+        fi
+        if [ -f "${logs_dir}/${jobid}_err" ]; then
+            completely_successful="no"
+        fi
+    done
+    if [ "${completely_successful}" == "yes" ]; then
+        colorprint "$(basename "${this_file}") utility finished successfully" "green"
+    else
+        echo "$(basename "${this_file}") utility finished"
+    fi
+else
+    echo "$(basename "${this_file}") utility finished. \
+Check the submitted job${plural} for results."
+fi
