changes to the update utility
* closes #4

* use "measure" as default FFTW wisdom rigor

* yet another fix for the weird "Format strings are only supported in Python 3.6 and greater" SyntaxError

* docs: add explanation of the --native-optimizations option to installer

* write CO𝘕CEPT to terminal using escape sequences;

* "yes" -> "True" in argparse_finished

Co-authored-by: Thomas Tram <thomas.tram@phys.au.dk>

diff --git a/concept/utilities/update b/concept/utilities/update
--- a/concept/utilities/update
+++ b/concept/utilities/update
@@ -24,9 +24,9 @@
 
 # This utility will update the CO𝘕CEPT or CLASS source files.
 # You can run this file directly as
-# utilities/update version [--reinstall] [--class]
+# utilities/update version [-y] [--class]
 # or invoke it via the concept script as
-# ./concept -u update version [--reinstall] [--class]
+# ./concept -u update version [-y] [--class]
 
 
 
@@ -54,14 +54,14 @@ if [ "${called_from_concept}" == "True" ]; then
 fi
 
 # Use Python's argparse module to handle command-line arguments
-argparse_finished="no"
+argparse_finished="False"
 argparse_exit_code=""
 args=$("${python}" -B -c "
 import argparse, sys
 # Setup command-line arguments
 parser = argparse.ArgumentParser(
     prog='$(basename "${this_file}")',
-    description='Run the CO𝘕CEPT $(basename "${this_file}") utility',
+    description='Run the ${esc_concept} $(basename "${this_file}") utility',
 )
 parser.add_argument(
     'version',
@@ -72,17 +72,22 @@ parser.add_argument(
     ),
 )
 parser.add_argument(
-    '--reinstall',
+    '-y', '--yes-to-defaults',
     default=False,
     action='store_true',
-    help='install requested version even when it equals the current version',
+    help=(
+        'accept default options on future queries '
+        '(passed on to installer script)'
+    ),
 )
 parser.add_argument(
     '--class',
     default=False,
     action='store_true',
-    help='update (and patch) CLASS rather than CO𝘕CEPT. '
-    'The version given should still be the CO𝘕CEPT version.',
+    help=(
+        'update (and patch) CLASS rather than ${esc_concept}. '
+        'The version given should still be the ${esc_concept} version.'
+    ),
 )
 # Enables Python to write directly to screen (stderr)
 # in case of help request.
@@ -101,15 +106,15 @@ else:
 sys.stdout = stdout_copy
 # Print out the arguments.
 # These will be captured in the Bash 'args' variable.
-print('argparse_finished=yes')
+print('argparse_finished=True')
 print('version=\"{}\"'.format(args.version))
-print('reinstall=\"{}\"'.format(args.reinstall))
+print('yes_to_defaults=\"{}\"'.format(args.yes_to_defaults))
 print('class=\"{}\"'.format(getattr(args, 'class')))
 " "$@" || echo "argparse_exit_code=$?")
 # Evaluate the handled arguments into this scope
 eval "${args}"
 # Exit if argparse exited without finishing
-if [ "${argparse_finished}" != "yes" ]; then
+if [ "${argparse_finished}" != "True" ]; then
     if [ -z "${argparse_exit_code}" ]; then
         argparse_exit_code=0
     fi
@@ -125,32 +130,6 @@ if [ "${called_from_concept}" != "True" ]; then
     "${concept}" -u="${this_file}" "$@"
     trap : 0
     exit 0
-fi
-
-# Determine the current CO𝘕CEPT version
-current_version="$("${concept}" -m "import commons; print(commons.__version__)" \
-    --local --pure-python | tail -n 1 || :)"
-
-# If the current CO𝘕CEPT version is already the requested version,
-# do nothing unless the --reinstall option was passed.
-if [[ "${current_version}" == *"."* ]] && [[ "${current_version}" != "v"* ]]; then
-    current_version="v${current_version}"
-fi
-if [[ "${version}" == *"."* ]] && [[ "${version}" != "v"* ]]; then
-    version="v${version}"
-fi
-if     [ "${version}" == "${current_version}" ] \
-    && [ "${version}" != "master"             ] \
-    && [ "${class}"   == "False"              ]; then
-    echo "CO𝘕CEPT version \"${version}\" already installed."
-    if [ "${reinstall}" == "True" ]; then
-        echo "A reinstallation will take place."
-    else
-        echo "If you wish to reinstall this version, \
-run the update utility with the --reinstall option."
-        trap : 0
-        exit 0
-    fi
 fi
 
 # Borrow some functions from the (current) installer script.
@@ -196,35 +175,142 @@ check_system_dependency "tar"  "${tar_package}"
 check_system_dependency "wget" "${wget_package}"
 
 # URLs to the CO𝘕CEPT source code and the installation script
+if [[ "${version}" == *"."* ]] && [[ "${version}" != "v"* ]]; then
+    version="v${version}"
+fi
 concept_url="https://github.com/jmd-dk/concept/archive/${version}.tar.gz"
 installer_url="https://raw.githubusercontent.com/jmd-dk/concept/${version}/installer"
 
 # Check that the specified version of CO𝘕CEPT exists
-if [[ "${version}" == *"."* ]]; then
-    if [[ "${version}" != "v"* ]]; then
-        version="v${version}"
-    fi
-fi
-validate_url "CONCEPT" "false"
+validate_url "CONCEPT" "False"
 if [ "${validate_url_status}" != "success" ]; then
-    colorprint "Could not find CO𝘕CEPT version ${version} online. \
+    colorprint "Could not find ${esc_concept} version ${version} online. \
 Check out https://github.com/jmd-dk/concept/ for available versions." "red"
     exit 1
 fi
 
+# Download the installer script from the specified version
+rm -rf "${top_dir}/tmp/installer"
+download "installer" "False" "${installer_url}" 2>/dev/null
+
+# Get and print out update information
+current_version="$("${concept}" -v | tail -n 1 || :)"
+if [[ "${current_version}" == *"."* ]] && [[ "${current_version}" != "v"* ]]; then
+    current_version="v${current_version}"
+fi
+if [ "${class}" == "False" ]; then
+    printf "Update ${esc_concept} \"${current_version}\" → \"${version}\"\n"
+else
+    current_class_version="$(                                 \
+        "${concept}"                                          \
+            -m "import linear; print(linear.class__VERSION_)" \
+            --pure-python                                     \
+        2>/dev/null                                           \
+        | tail -n 1                                           \
+    )"
+    if [ -z "${current_class_version}" ]; then
+        current_class_version="<unknown>"
+    fi
+    if [ -z "${class_version}" ]; then
+        class_version="$(grep "set_version.*class" "${top_dir}/tmp/installer/installer" \
+            | awk '{print $NF}')"
+    fi
+    eval "class_version=${class_version}"
+    if [[ "${class_version}" == *"."* ]] && [[ "${class_version}" != "v"* ]]; then
+        class_version="v${class_version}"
+    fi
+    export class_version="${class_version}"
+    printf "Update CLASS \"${current_class_version}\" (CLASS version) → \
+\"${class_version}\" (CLASS version) / \"${version}\" (${esc_concept} version)
+"
+fi
+if [ -z "${sleep_time}" ]; then
+    eval "$(grep "sleep_time=" "${installer}" | head -n 1)"
+fi
+sleep ${sleep_time}
+export sleep_time=0
+
 # If it is CLASS that is to be updated, do so and exit
 if [ "${class}" == "True" ]; then
+    # Backup entire CLASS directory and the classy site-packages files
+    mkdir -p "${top_dir}/tmp/backups"
+    rm -rf "${top_dir}/tmp/backups/class"
+    cp -r "${class_dir}" "${top_dir}/tmp/backups/class" 2>/dev/null || :
+    python_version_major_dot_minor="$( \
+        "${python}" -c "pass; \
+from sys import version_info as v; \
+print(str(v.major) + '.' + str(v.minor)); \
+")"
+    sitepackages_dir="${python_dir}/lib/python${python_version_major_dot_minor}/site-packages"
+    rm -rf "${top_dir}/tmp/backups/classy"
+    mkdir -p "${top_dir}/tmp/backups/classy"
+    cp -r "${sitepackages_dir}/classy"* "${top_dir}/tmp/backups/classy/" 2>/dev/null || :
+    # Remove CLASS and classy
     rm -rf "${class_dir}"
-    unset class_dir class_version
+    for f in "${sitepackages_dir}/classy"*; do
+        rm -rf "${f}" || :
+    done
+    # Install CLASS
+    rm -rf "${top_dir}/tmp/class"
+    class_dir_backup="${class_dir}"
+    unset class_dir
+    yes_to_defaults_flag=""
+    if [ "${yes_to_defaults}" == "True" ]; then
+        yes_to_defaults_flag="-y"
+    fi
     concept_install="False" class_install="True" python_dir="${python_dir}" \
+        check_other_running_installation="False" cleanup_tmp="False"        \
         say_welcome="False" say_copyright="False" say_goodbye="False"       \
-        bash <(wget -O- ${installer_url}) "${top_dir}"
+        bash "${top_dir}/tmp/installer/installer" ${yes_to_defaults_flag} "${top_dir}"
+    # Cleanup
+    rm -rf "${top_dir}/tmp/installer"
+    class_dir="${class_dir_backup}"
+    # Test CLASS
+    if [ -d "${blas_dir}" ]; then
+        export LD_LIBRARY_PATH="${blas_dir}/lib:${LD_LIBRARY_PATH}"
+    fi
+    test_success="True"
+    if ! "${python}" -B -c "
+import sys
+from classy import Class
+cosmo = Class()
+cosmo.compute()
+sys.exit(int(cosmo.get_background()['proper time [Gyr]'][-1]) != 13)
+" 2>/dev/null; then
+        test_success="False"
+    fi
+    # Exit on failure
+    if [ "${test_success}" == "False" ]; then
+        # Reinsert and remove the CLASS and classy backups before exiting
+        rm -rf "${class_dir}"
+        cp -r "${top_dir}/tmp/backups/class" "${class_dir}" 2>/dev/null || :
+        rm -rf "${top_dir}/tmp/backups/class"
+        cp -r "${top_dir}/tmp/backups/classy/"* "${sitepackages_dir}/" 2>/dev/null || :
+        rm -rf "${top_dir}/tmp/backups/classy"
+        if [ -d "${top_dir}/tmp/backups" ] && [ -z "$(ls -A "${top_dir}/tmp/backups")" ]; then
+            rm -rf "${top_dir}/tmp/backups"
+        fi
+        if [ -d "${top_dir}/tmp" ] && [ -z "$(ls -A "${top_dir}/tmp")" ]; then
+            rm -rf "${top_dir}/tmp"
+        fi
+        colorprint "The updated CLASS did not function correctly. \
+The update has been undone." "red"
+        exit 1
+    fi
     # Write out success message
     printf "
-CLASS with CO𝘕CEPT version \"${version}\" installed
+CLASS \"${class_version}\" (CLASS version) / \"${version}\" (${esc_concept} version) installed
 "
+    if [ -d "${top_dir}/tmp/backups" ]; then
+        printf "
+A backup of the existing CLASS code has been placed in
+\"${top_dir}/tmp/backups/class\"
+and
+\"${top_dir}/tmp/backups/classy\"
+"
+    fi
     if [ -d "${reusables_dir}/class" ] && [ -n "$(ls -A "${reusables_dir}/class")" ]; then
-        colorprint "\nNote!" "yellow"
+        colorprint "\nNote" "yellow"
         printf "You should remove cached CLASS dumps. You can do so by executing
 (cd \"${concept_dir}\" && source concept && make clean_class_reusables)\n\n"
     fi
@@ -232,41 +318,33 @@ CLASS with CO𝘕CEPT version \"${version}\" installed
     # Exit gracefully
     trap : 0
     exit 0
+else
+    # Cleanup
+    rm -rf "${top_dir}/tmp/installer"
 fi
-
-# Setup backup directory. For safety reasons, we do not allow
-# an update to be performed if this backup directory
-# is not empty.
-backup_dir="${top_dir}/.backup"
-if [ -d "${backup_dir}" ] && [ -n "$(ls -A "${backup_dir}")" ]; then
-    echo "A previously saved backup of CO𝘕CEPT is stored in \"${backup_dir}\". \
-For safety reasons I refuse to perform an update as long as this backup exists."
-    trap : 0
-    exit 0
-fi
-mkdir -p "${backup_dir}"
 
 # Download and extract the specified version of CO𝘕CEPT
-rm -rf "${top_dir}/tmp"
-mkdir "${top_dir}/tmp"
+mkdir -p "${top_dir}/tmp"
+rm -rf "${top_dir}/tmp/concept"
 download "CONCEPT"
 extract "CONCEPT"
 
-# Copy all original CO𝘕CEPT files also present in the new version
-# to the backup location.
+# Take backup of all original CO𝘕CEPT files also present in the new version
+backup_dir="${top_dir}/tmp/backups/concept"
+rm -rf "${backup_dir}"
+mkdir -p "${backup_dir}"
+new_files=()
 take_backup(){
     current_dir="$1"
     for file in "${current_dir}/"*; do
+        if [ ! -d "${top_dir}/${file}" ] && [ ! -f "${top_dir}/${file}" ]; then
+            new_files=("${new_files[@]}" "${file}")
+        fi
         if [ -d "${file}" ]; then
             take_backup "${file}"
-        else
-            # ${file} is a new file
-            if [ -f "${top_dir}/${file}" ]; then
-                # Old file with same name found.
-                # Copy it to the backup directory.
-                mkdir -p "${backup_dir}/$(dirname "${file}")"
-                cp "${top_dir}/${file}" "${backup_dir}/${file}"
-            fi
+        elif [ -f "${top_dir}/${file}" ]; then
+            mkdir -p "${backup_dir}/$(dirname "${file}")"
+            cp "${top_dir}/${file}" "${backup_dir}/${file}"
         fi
         current_dir="$1"
     done
@@ -279,7 +357,7 @@ for file in "${top_dir}/tmp/concept/"*; do
 done
 take_backup .
 
-# Move the new update utility, as bash might crash
+# Move the new update utility, as Bash might crash
 # if we removed the very script it is executing.
 new_update_utility="./concept/utilities/update"
 new_update_utility_moved="${this_file}_new"
@@ -291,24 +369,49 @@ fi
 # overwriting all files. Note that we do not include
 # the hidden (.paths, .env) files.
 cp -r ./* "${top_dir}/"
-
 # Cleanup
-rm -rf "${top_dir}/tmp"
+cd "${top_dir}"
+rm -rf "${top_dir}/tmp/concept"
+
+# Test CO𝘕CEPT
+test_success="True"
+if ! "${concept}" -c "H0 = 72*km/(s*Mpc)" -m "
+from commons import *
+h = H0/(100*units.km/(units.s*units.Mpc))
+sys.exit(not isclose(h, 0.72))
+" --pure-python >/dev/null 2>&1; then
+    test_success="False"
+fi
+# Exit on failure
+if [ "${test_success}" == "False" ]; then
+    # Reinsert and remove the CO𝘕CEPT backup
+    # and delete newly introduced files before exiting.
+    cp -r "${backup_dir}/"* "${top_dir}/"
+    rm -rf "${backup_dir}"
+    for file in "${new_files[@]}"; do
+        rm -rf "${top_dir}/${file}" || :
+    done
+    if [ -d "${top_dir}/tmp/backups" ] && [ -z "$(ls -A "${top_dir}/tmp/backups")" ]; then
+        rm -rf "${top_dir}/tmp/backups"
+    fi
+    if [ -d "${top_dir}/tmp" ] && [ -z "$(ls -A "${top_dir}/tmp")" ]; then
+        rm -rf "${top_dir}/tmp"
+    fi
+    colorprint "The updated ${esc_concept} did not function correctly. \
+The update has been undone." "red"
+    exit 1
+fi
 
 # Write out success message
-if [ "${version}" == "${current_version}" ]; then
-    printf "
-CO𝘕CEPT version \"${version}\" reinstalled
-"
-else
-    printf "
-CO𝘕CEPT updated to version \"${version}\"
-"
-fi
 printf "
-A backup of the existing CO𝘕CEPT source code has been placed in
+${esc_concept} version \"${version}\" installed
+"
+if [ -d "${backup_dir}" ]; then
+    printf "
+A backup of the existing ${esc_concept} source code has been placed in
 \"${backup_dir}\"
 "
+fi
 colorprint "$(basename "${this_file}") utility finished successfully" "green"
 
 # For graceful exit
