ready for release 0.1.0

diff --git a/concept/utilities/watch b/concept/utilities/watch
--- a/concept/utilities/watch
+++ b/concept/utilities/watch
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 # This file is part of CO𝘕CEPT, the cosmological 𝘕-body code in Python.
-# Copyright © 2015-2017 Jeppe Mosgaard Dakin.
+# Copyright © 2015–2018 Jeppe Mosgaard Dakin.
 #
 # CO𝘕CEPT is free software: You can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -30,7 +30,7 @@
 # You can run this file directly as
 # utilities/watch [jobid]
 # or invoke it via the concept script as
-# ./concept --util watch [jobid]
+# ./concept -u watch [jobid]
 
 
 
@@ -118,7 +118,7 @@ fi
 # If not called indirectly through the concept script,
 # call the concept script now.
 if [ "${called_from_concept}" != "True" ]; then
-    "${concept}" --util "${this_file}" "$@"
+    "${concept}" -u "${this_file}" "$@"
     trap : 0
     exit 0
 fi
@@ -129,10 +129,29 @@ if [ "${ssh}" != "True" ]; then
     exit 1
 fi
 
-# Check for the qstat command
-qstat_path="$(which qstat 2> /dev/null || :)"
-if [ -z "${qstat_path}" ]; then
-    colorprint "Error: Could not find the \"qstat\" command. Is PBS installed and on the PATH?" "red"
+# Detect what resource manager is used
+resource_manager="$(get_resource_manager)"
+if [ -z "${resource_manager}" ]; then
+    colorprint "Error: No resource manager found" "red"
+    exit 1
+fi
+# Check for the command which prints information about jobs
+if [ "${resource_manager}" == "slurm" ]; then
+    # Slurm is used. Check for the squeue command.
+    info_command="squeue"
+    if ! get_command "${info_command}" >/dev/null; then
+        colorprint "Error: Could not find the slurm '${info_command}' command" "red"
+        exit 1
+    fi
+elif [ "${resource_manager}" == "torque" ]; then
+    # Torque/PBS is used. Check for the qstat command.
+    info_command="qstat"
+    if ! get_command "${info_command}" >/dev/null; then
+        colorprint "Error: Could not find the torque/PBS '${info_command}' command" "red"
+        exit 1
+    fi
+else
+    colorprint "Error: Unrecognized resource manager \"${resource_manager}\"" "red"
     exit 1
 fi
 
@@ -142,24 +161,31 @@ fi
 my_username="$(whoami)"
 my_username="${my_username:0:15}"
 
-# Function that update the state variable by running the qstat command
+# Function that update the state variable
 update_job_info()
 {
     # Remove possible suffix on jobid
     jobid="${jobid%.*}"
     # Aquire information about submitted jobs.
-    # Revert the output of qstat,
-    # so that the newest jobs are in the top.
-    qstat_info="$(qstat | tac)"
+    # Revert the output so that the newest jobs are in the top.
+    info="$(${info_command} | tac)"
     # Reset the state variable
     state="None"
-    # Iterate through qstat output
+    # Iterate through the output
     while read -r line; do
-        jobid_line="$(echo "${line}" | awk '{print $1}')"
+        if [ "${resource_manager}" == "slurm" ]; then
+            jobid_line="$(echo "${line}" | awk '{print $1}')"
+        elif [ "${resource_manager}" == "torque" ]; then
+            jobid_line="$(echo "${line}" | awk '{print $1}')"
+        fi
         jobid_line="${jobid_line%.*}"
         if [ ${jobid_line} == ${jobid} ]; then
             # Submitted job with matching jobid found
-            username="$(echo "${line}" | awk '{print $3}')"
+            if [ "${resource_manager}" == "slurm" ]; then
+                username="$(echo "${line}" | awk '{print $4}')"
+            elif [ "${resource_manager}" == "torque" ]; then
+                username="$(echo "${line}" | awk '{print $3}')"
+            fi
             username="${username:0:15}"
             if [ "${username}" != "${my_username}" ]; then
                 colorprint "Job ${jobid} does not belong to you" "red"
@@ -169,11 +195,16 @@ update_job_info()
                 colorprint "Job ${jobid} is not a CO𝘕CEPT job" "red"
                 exit 1
             fi
-            state="$(echo "${line}" | awk '{print $5}')"
-            queue="$(echo "${line}" | awk '{print $6}')"
+            if [ "${resource_manager}" == "slurm" ]; then
+                state="$(echo "${line}" | awk '{print $5}')"
+                queue="$(echo "${line}" | awk '{print $2}')"
+            elif [ "${resource_manager}" == "torque" ]; then
+                state="$(echo "${line}" | awk '{print $5}')"
+                queue="$(echo "${line}" | awk '{print $6}')"
+            fi
             break
         fi
-    done <<< "${qstat_info}"
+    done <<< "${info}"
 }
 
 # Function for printing out an entire log file,
@@ -198,21 +229,35 @@ display()
 # find information about the job.
 if [ "${jobid}" == "__none__" ]; then
     # Aquire information about all submitted jobs
-    qstat_info="$(qstat)"
+    info="$(${info_command})"
     # Find all jobs submitted by the user.
     # Keep only the latest, running job.
     Njobs=0
     while read -r line; do
-        username="$(echo "${line}" | awk '{print $3}')"
+        if [ "${resource_manager}" == "slurm" ]; then
+            username="$(echo "${line}" | awk '{print $4}')"
+        elif [ "${resource_manager}" == "torque" ]; then
+            username="$(echo "${line}" | awk '{print $3}')"
+        fi
         username="${username:0:15}"
         if [ "${username}" == "${my_username}" ]; then
-            jobname="$(echo "${line}" | awk '{print $2}')"
+            if [ "${resource_manager}" == "slurm" ]; then
+                jobname="$(echo "${line}" | awk '{print $3}')"
+            elif [ "${resource_manager}" == "torque" ]; then
+                jobname="$(echo "${line}" | awk '{print $2}')"
+            fi
             if [[ "${jobname}" == *"CONCEPT"* ]]; then
                 # CO𝘕CEPT job submitted by the user found
                 ((Njobs += 1))
-                jobid_i="$(echo "${line}" | awk '{print $1}')"
-                state_i="$(echo "${line}" | awk '{print $5}')"
-                queue_i="$(echo "${line}" | awk '{print $6}')"
+                if [ "${resource_manager}" == "slurm" ]; then
+                    jobid_i="$(echo "${line}" | awk '{print $1}')"
+                    state_i="$(echo "${line}" | awk '{print $5}')"
+                    queue_i="$(echo "${line}" | awk '{print $2}')"
+                elif [ "${resource_manager}" == "torque" ]; then
+                    jobid_i="$(echo "${line}" | awk '{print $1}')"
+                    state_i="$(echo "${line}" | awk '{print $5}')"
+                    queue_i="$(echo "${line}" | awk '{print $6}')"
+                fi
                 if [ ${Njobs} == 1 ] || [ "${state_i}" == "R" ]; then
                     jobid="${jobid_i}"
                     state="${state_i}"
@@ -220,7 +265,7 @@ if [ "${jobid}" == "__none__" ]; then
                 fi
             fi
         fi
-    done <<< "${qstat_info}"
+    done <<< "${info}"
     # Remove possible suffix on jobid
     jobid="${jobid%.*}"
     # Print out message for Njobs != 1
@@ -255,25 +300,47 @@ state_last=""
 inform_on_new_state()
 {
     if [ "${state}" != "${state_last}" ]; then
-        case "${state}" in
-            "C"    ) echo "Job ${jobid} is completed after having run";;
-            "E"    ) echo "Job ${jobid} is exiting after having run";;
-            "H"    ) echo "Job ${jobid} is held";;
-            "Q"    ) echo "Job ${jobid} is queued in ${queue}";;
-            "R"    ) echo "Job ${jobid} is running in queue ${queue}";;
-            "T"    ) echo "Job ${jobid} is being moved to a new location";;
-            "W"    ) echo "Job ${jobid} is waiting for its executing time to be reached";;
-            "S"    ) echo "Job ${jobid} is suspend";;
-            "None" ) echo "Job ${jobid} has finished running";;
-            ""     ) echo "Job ${jobid} is in an unspecified state";;
-            *      ) echo "Job ${jobid} is in the unknown state \"${state}\"";;
-        esac
+        if [ "${resource_manager}" == "slurm" ]; then
+            case "${state}" in
+                "BF"   ) echo "Job ${jobid} terminated due to launch failure";;
+                "CA"   ) echo "Job ${jobid} was explicitly cancelled";;
+                "CD"   ) echo "Job ${jobid} is completed after having run";;
+                "CF"   ) echo "Job ${jobid} is configuring resources";;
+                "CG"   ) echo "Job ${jobid} is exiting after having run";;
+                "F"    ) echo "Job ${jobid} terminated due to an error";;
+                "NF"   ) echo "Job ${jobid} terminated due to failure of one or more nodes";;
+                "PD"   ) echo "Job ${jobid} is queued in ${queue}";;
+                "PR"   ) echo "Job ${jobid} terminated due to preemption";;
+                "R"    ) echo "Job ${jobid} is running in queue ${queue}";;
+                "SE"   ) echo "Job ${jobid} was requeued in a special state";;
+                "ST"   ) echo "Job ${jobid} has stopped with the SIGSTOP signal";;
+                "S"    ) echo "Job ${jobid} has been suspended";;
+                "TO"   ) echo "Job ${jobid} was terminated upon reaching its time limit";;
+                "None" ) echo "Job ${jobid} has finished running";;
+                ""     ) echo "Job ${jobid} is in an unspecified state";;
+                *      ) echo "Job ${jobid} is in the unknown state \"${state}\"";;
+            esac
+        elif [ "${resource_manager}" == "torque" ]; then
+            case "${state}" in
+                "C"    ) echo "Job ${jobid} is completed after having run";;
+                "E"    ) echo "Job ${jobid} is exiting after having run";;
+                "H"    ) echo "Job ${jobid} is held";;
+                "Q"    ) echo "Job ${jobid} is queued in ${queue}";;
+                "R"    ) echo "Job ${jobid} is running in queue ${queue}";;
+                "T"    ) echo "Job ${jobid} is being moved to a new location";;
+                "W"    ) echo "Job ${jobid} is waiting for its executing time to be reached";;
+                "S"    ) echo "Job ${jobid} is suspend";;
+                "None" ) echo "Job ${jobid} has finished running";;
+                ""     ) echo "Job ${jobid} is in an unspecified state";;
+                *      ) echo "Job ${jobid} is in the unknown state \"${state}\"";;
+            esac
+        fi
         state_last="${state}"
     fi
 }
 
 # Function for checking if the job suddenly finished.
-# Do not call this function after beginning reading the logfile.
+# Do not call this function after beginning reading the log file.
 check_suddenly_finished()
 {
     update_job_info
@@ -283,7 +350,7 @@ check_suddenly_finished()
         if [ -f "${logs_dir}/${jobid}" ]; then
             display "${logs_dir}/${jobid}"
         else
-            echo "Job ${jobid} has finished running, but no logfile is to be found. Curious ..."
+            echo "Job ${jobid} has finished running, but no log file is to be found. Curious ..."
         fi
         trap : 0
         exit 0
@@ -305,11 +372,11 @@ if [ "${state}" != "R" ]; then
     sleep ${sleep_barely}
     check_suddenly_finished
     if [ "${state}" != "R" ]; then
-        # Wait a small time before calling qstat again
+        # Wait a small time before calling the info command again
         sleep ${sleep_little}
         check_suddenly_finished
         while [ "${state}" != "R" ] ; do   
-            # Wait a long time before calling qstat again
+            # Wait a long time before calling the info command again
             sleep ${sleep_much}
             check_suddenly_finished
         done
@@ -317,7 +384,7 @@ if [ "${state}" != "R" ]; then
 fi
 state_last="R"
 
-# Job running. Wait for logfile to be created.
+# Job running. Wait for log file to be created.
 if [ ! -f "${logs_dir}/${jobid}" ]; then
     sleep ${sleep_barely}
 fi
@@ -333,7 +400,7 @@ while [ ! -f "${logs_dir}/${jobid}" ]; do
     fi
 done
 
-# Logfile created. Continuously print out its tail until end of job
+# Log file created. Continuously print out its tail until end of job
 echo
 display "${logs_dir}/${jobid}"
 tail -n 0 --follow --sleep-interval=${sleep_little} "${logs_dir}/${jobid}" &
@@ -341,12 +408,12 @@ tail_pid=$!
 update_job_info
 inform_on_new_state
 if [ "${state}" != "None" ]; then
-    # Wait a small time before calling qstat again
+    # Wait a small time before calling the info command again
     sleep ${sleep_little}
     update_job_info
     inform_on_new_state
     while [ "${state}" != "None" ]; do
-        # Wait a long time before calling qstat again
+        # Wait a long time before calling the info command again
         sleep ${sleep_much}
         update_job_info
         inform_on_new_state
