updated readme

diff --git a/source/run b/source/run
--- a/source/run
+++ b/source/run
@@ -16,21 +16,6 @@ params=${this_dir}/params/default
 main=${this_dir}/main.py
 pure_python=0
 
-# Set up error trapping
-ctrl_c()
-{
-    trap : 0
-    exit 2
-}
-abort()
-{
-    printf "\e[1m\e[91mAn error occurred!\e[0m\n" >&2
-    exit 1
-}
-trap 'ctrl_c' SIGINT
-trap 'abort' EXIT
-set -e
-
 # Use Python's argparse module to handle command-line arguments
 args=(`${python} -c "
 import argparse
@@ -42,9 +27,9 @@ if any(h in sys.argv for h in ['-h', '--he', '--hel', '--help']):
 # Set the filename of the script
 sys.argv[0] = '${this_file}'
 # Setup command-line arguments
-parser = argparse.ArgumentParser(description='Run the Nbody code.')
+parser = argparse.ArgumentParser(description='Run the N-body code.')
 parser.add_argument('-n', '--nprocs',
-                    help='Number of processes. Must be a power of 2.',
+                    help='Number of processes.',
                     type=int,
                     default=${nprocs},
                     )
@@ -87,6 +72,22 @@ unspecified_params=${args[5]}
 if [ ${#args[@]} -ne 6 ]; then
     exit 1
 fi
+
+# Set up error trapping
+ctrl_c()
+{
+    trap : 0
+    exit 2
+}
+abort()
+{
+    printf "\e[1m\e[91mAn error occurred!\e[0m\n" >&2
+    exit 1
+}
+trap 'ctrl_c' SIGINT
+trap 'abort' EXIT
+set -e
+
 # Print warnings for unspecified parameters
 if [ ${unspecified_nprocs} == 1 ]; then
     echo "Number of processes not specified - Will use ${nprocs}"
